-- Khfresh BentoGridStyle
-- Dedicated UI library for Khfresh Hub.
-- Icons are stored as original packed 24x24 alpha bitmaps generated for this library.
-- EditableImage is the smooth renderer; a compact 8x8 pixel fallback is used only when unavailable.

local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")
local Players = game:GetService("Players")
local AssetService = game:GetService("AssetService")

local LocalPlayer = Players.LocalPlayer

local function resolveParent()
    local ok, parent = pcall(function()
        if type(gethui) == "function" then
            local h = gethui()
            if h then return h end
        end
        return game:GetService("CoreGui")
    end)
    if ok and parent then return parent end
    return LocalPlayer:WaitForChild("PlayerGui")
end

local GuiParent = resolveParent()

local UI = {
    _version = "6.0.0-khfresh-bento-packed",
    _windows = {},
    _notifyGui = nil,
    _iconImages = {},
}

local THEMES = {
    Bento = {
        canvas = Color3.fromRGB(22, 24, 30), shell = Color3.fromRGB(25, 28, 35),
        rail = Color3.fromRGB(21, 24, 30), header = Color3.fromRGB(30, 34, 42),
        card = Color3.fromRGB(31, 35, 43), row = Color3.fromRGB(35, 40, 49),
        rowHover = Color3.fromRGB(42, 48, 59), rowPressed = Color3.fromRGB(49, 56, 68),
        line = Color3.fromRGB(67, 75, 89), lineSoft = Color3.fromRGB(50, 57, 68),
        text = Color3.fromRGB(244, 247, 252), secondary = Color3.fromRGB(191, 198, 210),
        muted = Color3.fromRGB(132, 141, 157), accent = Color3.fromRGB(106, 192, 255),
        accentSoft = Color3.fromRGB(43, 82, 116), success = Color3.fromRGB(104, 216, 157),
        danger = Color3.fromRGB(245, 118, 128), warning = Color3.fromRGB(244, 195, 106),
    },
    Dark = {
        canvas = Color3.fromRGB(17, 19, 24), shell = Color3.fromRGB(21, 24, 30),
        rail = Color3.fromRGB(18, 21, 26), header = Color3.fromRGB(25, 29, 35),
        card = Color3.fromRGB(27, 31, 38), row = Color3.fromRGB(31, 36, 44),
        rowHover = Color3.fromRGB(38, 44, 54), rowPressed = Color3.fromRGB(46, 53, 64),
        line = Color3.fromRGB(57, 64, 75), lineSoft = Color3.fromRGB(43, 49, 59),
        text = Color3.fromRGB(240, 243, 248), secondary = Color3.fromRGB(181, 188, 201),
        muted = Color3.fromRGB(124, 133, 148), accent = Color3.fromRGB(98, 182, 246),
        accentSoft = Color3.fromRGB(39, 74, 103), success = Color3.fromRGB(99, 208, 151),
        danger = Color3.fromRGB(240, 110, 121), warning = Color3.fromRGB(238, 188, 96),
    },
}

local currentTheme = "Bento"
local C = {}
local function applyTheme(name)
    if not THEMES[name] then name = "Bento" end
    currentTheme = name
    for k, v in pairs(THEMES[name]) do C[k] = v end
end
applyTheme("Bento")

local Motion = {
    fast = TweenInfo.new(0.10, Enum.EasingStyle.Quad, Enum.EasingDirection.Out),
    base = TweenInfo.new(0.18, Enum.EasingStyle.Quad, Enum.EasingDirection.Out),
    smooth = TweenInfo.new(0.26, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
    spring = TweenInfo.new(0.32, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
}

local function make(className, props, parent)
    local obj = Instance.new(className)
    if props then
        for k, v in pairs(props) do
            pcall(function() obj[k] = v end)
        end
    end
    if parent then obj.Parent = parent end
    return obj
end

local function corner(parent, r)
    return make("UICorner", {CornerRadius = UDim.new(0, r or 12)}, parent)
end

local function outline(parent, color, transparency, thickness)
    return make("UIStroke", {
        Color = color or C.line,
        Transparency = transparency == nil and 0.42 or transparency,
        Thickness = thickness or 1,
    }, parent)
end

local function pad(parent, l, r, t, b)
    return make("UIPadding", {
        PaddingLeft = UDim.new(0, l or 0), PaddingRight = UDim.new(0, r or 0),
        PaddingTop = UDim.new(0, t or 0), PaddingBottom = UDim.new(0, b or 0),
    }, parent)
end

local function list(parent, gap)
    local lay = make("UIListLayout", {
        FillDirection = Enum.FillDirection.Vertical,
        SortOrder = Enum.SortOrder.LayoutOrder,
        Padding = UDim.new(0, gap or 8),
    }, parent)
    return lay
end

local function tween(obj, info, props)
    if not obj or not obj.Parent then return end
    local ok, tw = pcall(function() return TweenService:Create(obj, info or Motion.base, props) end)
    if ok and tw then tw:Play(); return tw end
end

local function text(parent, value, size, color, bold)
    return make("TextLabel", {
        BackgroundTransparency = 1, BorderSizePixel = 0, Text = tostring(value or ""),
        TextColor3 = color or C.text, TextSize = size or 13,
        Font = bold and Enum.Font.GothamMedium or Enum.Font.Gotham,
        TextXAlignment = Enum.TextXAlignment.Left, TextYAlignment = Enum.TextYAlignment.Center,
        TextTruncate = Enum.TextTruncate.AtEnd,
    }, parent)
end

local function hitButton(parent, z)
    return make("TextButton", {
        Text = "", BackgroundTransparency = 1, BorderSizePixel = 0,
        AutoButtonColor = false, Size = UDim2.fromScale(1, 1), ZIndex = z or 50,
    }, parent)
end

local function safeName(s)
    return tostring(s or "Element"):gsub("[^%w_]+", "_")
end

local function isTouchDevice()
    return UserInputService.TouchEnabled == true
end

local function getViewport()
    local cam = workspace.CurrentCamera
    return cam and cam.ViewportSize or Vector2.new(1280, 720)
end

local function isMobile()
    local vp = getViewport()
    return vp.X < 720 or (isTouchDevice() and vp.X < 960)
end

-- ============================================================
-- KHfresh dedicated packed bitmap icon set (generated independently)
-- ============================================================
local PACKED_ICONS = {
    ["x"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAbN1zAAAAAAAAAAAAAAAAAHPdbAAAAAAB3f/+egAAAAAAAAAAAAAAev7/3QEAAAAAc/7//noAAAAAAAAAAAB6/v/+cwAAAAAAAHr+//56AAAAAAAAAHr+//56AAAAAAAAAAB6/v/+egAAAAAAev7//noAAAAAAAAAAAAAev7//noAAAB6/v/+egAAAAAAAAAAAAAAAHr+//56AXr+//56AAAAAAAAAAAAAAAAAAB6/v/+uf7//noAAAAAAAAAAAAAAAAAAAAAev7////+egAAAAAAAAAAAAAAAAAAAAAAAbn///+5AQAAAAAAAAAAAAAAAAAAAAAAev7////+egAAAAAAAAAAAAAAAAAAAAB6/v/+uf7//noAAAAAAAAAAAAAAAAAAHr+//56AXr+//56AAAAAAAAAAAAAAAAev7//noAAAB6/v/+egAAAAAAAAAAAAB6/v/+egAAAAAAev7//noAAAAAAAAAAHr+//56AAAAAAAAAHr+//56AAAAAAAAc/7//noAAAAAAAAAAAB6/v/+cwAAAAAB3f/+egAAAAAAAAAAAAAAev7/3QEAAAAAbN1zAAAAAAAAAAAAAAAAAHPdbAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["minus"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABjI1NTU1NTU1NTU1NTU1NTUyBgAAAAAGzP//////////////////////zAYAAAAv/////////////////////////y8AAAAGzP//////////////////////zAYAAAAABjI1NTU1NTU1NTU1NTU1NTUyBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["plus"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGLwYAAAAAAAAAAAAAAAAAAAAAAAAAAAbM/8wGAAAAAAAAAAAAAAAAAAAAAAAAADL///8yAAAAAAAAAAAAAAAAAAAAAAAAADX///81AAAAAAAAAAAAAAAAAAAAAAAAADX///81AAAAAAAAAAAAAAAAAAAAAAAAADX///81AAAAAAAAAAAAAAAAAAAAAAAAADX///81AAAAAAAAAAAAAAAAAAAAAAAAADX///81AAAAAAAAAAAAAAAABjI1NTU1NVz///9cNTU1NTUyBgAAAAAGzP//////////////////////zAYAAAAv/////////////////////////y8AAAAGzP//////////////////////zAYAAAAABjI1NTU1NVz///9cNTU1NTUyBgAAAAAAAAAAAAAAADX///81AAAAAAAAAAAAAAAAAAAAAAAAADX///81AAAAAAAAAAAAAAAAAAAAAAAAADX///81AAAAAAAAAAAAAAAAAAAAAAAAADX///81AAAAAAAAAAAAAAAAAAAAAAAAADX///81AAAAAAAAAAAAAAAAAAAAAAAAADL///8yAAAAAAAAAAAAAAAAAAAAAAAAAAbM/8wGAAAAAAAAAAAAAAAAAAAAAAAAAAAGLwYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["chevron-down"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAETAQAAAAAAAAAAAAAAARMBAAAAAAAAAa79swoAAAAAAAAAAAAKs/2uAQAAAAAAE/3//7kKAAAAAAAAAAq5///9EwAAAAAAAbP///+5CgAAAAAACrn///+zAQAAAAAAAAq5////uQoAAAAKuf///7kKAAAAAAAAAAAKuf///7kKAAq5////uQoAAAAAAAAAAAAACrn///+5FLn///+5CgAAAAAAAAAAAAAAAAq5////7v///7kKAAAAAAAAAAAAAAAAAAAKuf//////uQoAAAAAAAAAAAAAAAAAAAAACrn///+5CgAAAAAAAAAAAAAAAAAAAAAAAAqz/bMKAAAAAAAAAAAAAAAAAAAAAAAAAAABEwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["chevron-right"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEwEAAAAAAAAAAAAAAAAAAAAAAAAAAAGu/bMKAAAAAAAAAAAAAAAAAAAAAAAAABP9//+5CgAAAAAAAAAAAAAAAAAAAAAAAAGz////uQoAAAAAAAAAAAAAAAAAAAAAAAAKuf///7kKAAAAAAAAAAAAAAAAAAAAAAAACrn///+5CgAAAAAAAAAAAAAAAAAAAAAAAAq5////uQoAAAAAAAAAAAAAAAAAAAAAAAAKuf///7kKAAAAAAAAAAAAAAAAAAAAAAAACrn///+zAQAAAAAAAAAAAAAAAAAAAAAAABTu///9EwAAAAAAAAAAAAAAAAAAAAAACrn///+zAQAAAAAAAAAAAAAAAAAAAAAKuf///7kKAAAAAAAAAAAAAAAAAAAAAAq5////uQoAAAAAAAAAAAAAAAAAAAAACrn///+5CgAAAAAAAAAAAAAAAAAAAAAKuf///7kKAAAAAAAAAAAAAAAAAAAAAAGz////uQoAAAAAAAAAAAAAAAAAAAAAABP9//+5CgAAAAAAAAAAAAAAAAAAAAAAAAGu/bMKAAAAAAAAAAAAAAAAAAAAAAAAAAABEwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["check"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4eAAAAAAAAAAAAAAAAAAAAAAAAAAAAXvv7VwAAAAAAAAAAAAAAAAAAAAAAAAA09f//rgAAAAAAAAAAAAAAAAAAAAAAABXf///+WQAAAAAAAAAAAAAAAAAAAAAABbv///+VAQAAAAAAAAAAAAAAAAAAAAAAiv///8MHAAAAAAAAAAAAAAAAAAAAAABX/f//5RsAAAAAAAAAFZmZFQAAAAAAAC3y///4PAAAAAAAAAAAmf//0RYAAAAAEdn///5rAAAAAAAAAAAAmf///9EWAAADsv///58BAAAAAAAAAAAAFdH////RFgCA////ywoAAAAAAAAAAAAAABbR////0V/8///qIAAAAAAAAAAAAAAAAAAW0f////3///tFAAAAAAAAAAAAAAAAAAAAFtH//////3UAAAAAAAAAAAAAAAAAAAAAABbR////qQIAAAAAAAAAAAAAAAAAAAAAAAAWzv/MDQAAAAAAAAAAAAAAAAAAAAAAAAAABi8GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["circle-check"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABTJXZlcyBQAAAAAAAAAAAAAAAAAAABmN6P//////6I0ZAAAAAAAAAAAAAAAAXu/////////////vXgAAAAAAAAAAAAB9/v//97B6aXqw9////n0AAAAAAAAAAF7+//6kGwAAAAAAG6T+//5eAAAAAAAAGe///nkBAAAAAAAAADHy///vGQAAAAAAjf//pAEAAAAAAAAAJuf/////jQAAAAAF6P/3GwAAAAAAAAAd3v//7ff/6AUAAAAy//+wAAQAAAAAABXU///zO7D//zIAAABX//97jPWUAwAAD8r///hIAHr//1cAAABm//9t9f//nAMKv///+1YAAGn//2YAAABX//97lP///5yx///9ZAAAAHr//1cAAAAy//+wA5z///////5zAAAAALD//zIAAAAF6P/3GwOc/////4QAAAAAG/f/6AUAAAAAjf//pAEDnP//lQEAAAABpP//jQAAAAAAGe///nkBA2JiAwAAAAF5/v/vGQAAAAAAAF7+//6kGwAAAAAAG6T+//5eAAAAAAAAAAB9/v//97B6aXqw9////n0AAAAAAAAAAAAAXu/////////////vXgAAAAAAAAAAAAAAABmN6P//////6I0ZAAAAAAAAAAAAAAAAAAAABTJXZlcyBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["play"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAETAQAAAAAAAAAAAAAAAAAAAAAAAAAAAa79vygAAAAAAAAAAAAAAAAAAAAAAAAAFv7///Z8BwAAAAAAAAAAAAAAAAAAAAAAGf7/////0joAAAAAAAAAAAAAAAAAAAAAGf7///////yTDwAAAAAAAAAAAAAAAAAAGf7//rb+////4U8BAAAAAAAAAAAAAAAAGf7//hpP4f////6qGgAAAAAAAAAAAAAAGf7//hkAD5P8////7WYCAAAAAAAAAAAAGf7//hkAAAA60v////+vAQAAAAAAAAAAGf7//hkAAAAADtH////9EwAAAAAAAAAAGf7//hkAAAA60v////+vAQAAAAAAAAAAGf7//hkAD5P8////7WYCAAAAAAAAAAAAGf7//hpP4f////6qGgAAAAAAAAAAAAAAGf7//rb+////4U8BAAAAAAAAAAAAAAAAGf7///////yTDwAAAAAAAAAAAAAAAAAAGf7/////0joAAAAAAAAAAAAAAAAAAAAAFv7///Z8BwAAAAAAAAAAAAAAAAAAAAAAAa79vygAAAAAAAAAAAAAAAAAAAAAAAAAAAETAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["settings"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4ezgAAAAAAAAAAAAAAAAAAAAAAAAAADj6//o4AAAAAAAAAAAAAAAAAAAAAAAAAH3///99AAAAAAAAAAAAAAAAACe7zVEAAID///+AAABRzbsnAAAAAAAAALv///pZAH3///99AFn6//+7AAAAAAAAAM3////6Rof///+HRvr////NAAAAAAAAAFH6////+///////+/////pRAAAAAAAAAABZ+v//////////////+lkAAAAAAAAAAAAARvv////////////7RgAAAAAAAAA4fYB9h/////yQT5D8////h32AfTgAADj6/////////5AAAACQ//////////o4AHv//////////08AAABP//////////97ADj6/////////5AAAACQ//////////o4AAA4fYB9h/////yQT5D8////h32AfTgAAAAAAAAARvv////////////7RgAAAAAAAAAAAABZ+v//////////////+lkAAAAAAAAAAFH6////+///////+/////pRAAAAAAAAAM3////6Rof///+HRvr////NAAAAAAAAALv///pZAH3///99AFn6//+7AAAAAAAAACe7zVEAAID///+AAABRzbsnAAAAAAAAAAAAAAAAAH3///99AAAAAAAAAAAAAAAAAAAAAAAAADj6//o4AAAAAAAAAAAAAAAAAAAAAAAAAAA4ezgAAAAAAAAAAAAA",
    ["search"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABZpn7OfaRYAAAAAAAAAAAAAAAAAAAADevP///////N6AwAAAAAAAAAAAAAAAAOm////////////pgMAAAAAAAAAAAAAAHr////+1rfW/v///3oAAAAAAAAAAAAAFvP//+xKAQABSuz///MWAAAAAAAAAAAAaf///koAAAAAAEr+//9pAAAAAAAAAAAAn///1gEAAAAAAAHW//+fAAAAAAAAAAAAs///twAAAAAAAAC3//+zAAAAAAAAAAAAn///1gEAAAAAAAHW//+fAAAAAAAAAAAAaf///koAAAAAAEr+//9pAAAAAAAAAAAAFvP//+xKAQABSuz///MWAAAAAAAAAAAAAHr////+1rfW/v///+coAAAAAAAAAAAAAAOm///////////////kKAAAAAAAAAAAAAADevP///////Pn////5CgAAAAAAAAAAAAAABZpn7OfaRYo5P///+QoAAAAAAAAAAAAAAAAAAAAAAAAKOT////kKAAAAAAAAAAAAAAAAAAAAAAAACjk////4xIAAAAAAAAAAAAAAAAAAAAAAAAo5P///0YAAAAAAAAAAAAAAAAAAAAAAAAAKOP/4hIAAAAAAAAAAAAAAAAAAAAAAAAAABJGEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["info"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABTJXZlcyBQAAAAAAAAAAAAAAAAAAABmN6P//////6I0ZAAAAAAAAAAAAAAAAXu/////////////vXgAAAAAAAAAAAAB9/v//97B6aXqw9////n0AAAAAAAAAAF7+//6kGwAxnDEAG6T+//5eAAAAAAAAGe///nkBAACc/5wAAAF5/v/vGQAAAAAAjf//pAEAAAAxnzEAAAABpP//jQAAAAAF6P/3GwAAAACM9YwAAAAAG/f/6AUAAAAy//+wAAAAAAX3//cFAAAAALD//zIAAABX//96AAAAAAb5//kGAAAAAHr//1cAAABm//9pAAAAAAb5//kGAAAAAGn//2YAAABX//96AAAAAAb5//kGAAAAAHr//1cAAAAy//+wAAAAAAb5//kGAAAAALD//zIAAAAF6P/3GwAAAAb5//kGAAAAG/f/6AUAAAAAjf//pAEAAAb5//kGAAABpP//jQAAAAAAGe///nkBAAX3//cFAAF5/v/vGQAAAAAAAF7+//6kGwCM9YwAG6T+//5eAAAAAAAAAAB9/v//97B7bXuw9////n0AAAAAAAAAAAAAXu/////////////vXgAAAAAAAAAAAAAAABmN6P//////6I0ZAAAAAAAAAAAAAAAAAAAABTJXZlcyBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["house"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEwEAAAAAAAAAAAAAAAAAAAAAAAAAABC2/bYQAAAAAAAAAAAAAAAAAAAAAAAAHdD////QHQAAAAAAAAAAAAAAAAAAAAAw4v//////4jAAAAAAAAAAAAAAAAAAAEbw////1f////BGAAAAAAAAAAAAAAAAYfn///6AA4D+///5YQAAAAAAAAAAAAKA/v//+WEAAABh+f///oACAAAAAAAABp7////wRgAAAAAARvD///+eBgAAAAABsf////47AAAAAAAAADv+////sQEAAAAT/f////4ZAAAAAAAAABn+/////RMAAAABrv3///4ZARMBAAETARn+///9rgEAAAAAASn+//4brv2uA679rhv+//4pAQAAAAAAABn+//4w/v/+Lf7//jD+//4ZAAAAAAAAABn+//4y/v/+Mv7//jL+//4ZAAAAAAAAABn+//4y/v/+Mv7//jL+//4ZAAAAAAAAABn+//4y/v/+Mv7//jL+//4ZAAAAAAAAABn+//4//v/+P/7//j/+//4ZAAAAAAAAABn+///+/////v////7///4ZAAAAAAAAABb+//////////////////4WAAAAAAAAAAGu/v7+/v7+/v7+/v7+/q4BAAAAAAAAAAABFhkZGRkZGRkZGRkZFgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["layout-dashboard"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAbOLm5ubm5ubm5ubm5ubm5ubibAAAAAAB4v//////////////////////4gEAAAAB5v/45ubm5ub4//jm5ubm5vj/5gEAAAAB5v/mAgEBAQLm/+YCAQEBAub/5gEAAAAB5v/mAQAAAAHm/+YBAAAAAeb/5gEAAAAB5v/mAQAAAAHm/+YBAAAAAeb/5gEAAAAB5v/mAQAAAAHm/+YBAAAAAeb/5gEAAAAB5v/mAgEBAQLm/+YCAQEBAub/5gEAAAAB5v/45ubm5ub4//jm5ubm5vj/5gEAAAAB5v//////////////////////5gEAAAAB5v/45ubm5ub4//jm5ubm5vj/5gEAAAAB5v/mAgEBAQLm/+YCAQEBAub/5gEAAAAB5v/mAQAAAAHm/+YBAAAAAeb/5gEAAAAB5v/mAQAAAAHm/+YBAAAAAeb/5gEAAAAB5v/mAQAAAAHm/+YBAAAAAeb/5gEAAAAB5v/mAgEBAQLm/+YCAQEBAub/5gEAAAAB5v/45ubm5ub4//jm5ubm5vj/5gEAAAAB4v//////////////////////4gEAAAAAbOLm5ubm5ubm5ubm5ubm5ubibAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["panel-left"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAbOLm5ubm5ubm5ubm5ubm5ubibAAAAAAB4v//////////////////////4gEAAAAB5v/45ubm+P/45ubm5ubm5vj/5gEAAAAB5v/mAgEC5v/mAgEBAQEBAub/5gEAAAAB5v/mAQAB5v/mAQAAAAAAAeb/5gEAAAAB5v/mAQAB5v/mAQAAAAAAAeb/5gEAAAAB5v/mAQAB5v/mAQAAAAAAAeb/5gEAAAAB5v/mAQAB5v/mAQAAAAAAAeb/5gEAAAAB5v/mAQAB5v/mAQAAAAAAAeb/5gEAAAAB5v/mAQAB5v/mAQAAAAAAAeb/5gEAAAAB5v/mAQAB5v/mAQAAAAAAAeb/5gEAAAAB5v/mAQAB5v/mAQAAAAAAAeb/5gEAAAAB5v/mAQAB5v/mAQAAAAAAAeb/5gEAAAAB5v/mAQAB5v/mAQAAAAAAAeb/5gEAAAAB5v/mAQAB5v/mAQAAAAAAAeb/5gEAAAAB5v/mAgEC5v/mAgEBAQEBAub/5gEAAAAB5v/45ubm+P/45ubm5ubm5vj/5gEAAAAB4v//////////////////////4gEAAAAAbOLm5ubm5ubm5ubm5ubm5ubibAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["panels-top-left"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAbOLm5ubm5ubm5ubm5ubm5ubibAAAAAAB4v//////////////////////4gEAAAAB5v/45ubm5ubm5ubm5ubm5vj/5gEAAAAB5v/mAgEBAQEBAQEBAQEBAub/5gEAAAAB5v/mAQAAAAAAAAAAAAAAAeb/5gEAAAAB5v/mAgEBAQEBAQEBAQEBAub/5gEAAAAB5v/45ubm5ubm5ubm5ubm5vj/5gEAAAAB5v//////////////////////5gEAAAAB5v/45ubm5vj/+Obm5ubm5vj/5gEAAAAB5v/mAgEBAub/5gIBAQEBAub/5gEAAAAB5v/mAQAAAeb/5gEAAAAAAeb/5gEAAAAB5v/mAQAAAeb/5gEAAAAAAeb/5gEAAAAB5v/mAQAAAeb/5gEAAAAAAeb/5gEAAAAB5v/mAQAAAeb/5gEAAAAAAeb/5gEAAAAB5v/mAQAAAeb/5gEAAAAAAeb/5gEAAAAB5v/mAgEBAub/5gIBAQEBAub/5gEAAAAB5v/45ubm5vj/+Obm5ubm5vj/5gEAAAAB4v//////////////////////4gEAAAAAbOLm5ubm5ubm5ubm5ubm5ubibAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["fish"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQYGBgYGBgUAAAAAAAAAAAAAAAAAAAOU9/n5+fn5+feQAQAAAAAAAAAAAAAAA5z////////////+bAAAAAAAAAAAAAADnP////n5+fn5+v//+T4AAAAAAAAAAAOc////nAcGBgYGQub//+cdAAAAAAAAA5z////5BwAAAAAQ7PPq///ICQAAAAAAlP/////5BgAAAAADjo5C+f//mgAAAAAE9f/////5BgAAAAAAAAAAnv//9QQAAAAAlP/////5BgAAAAAAAAA++f//mgAAAAAAA5z////5BwAAAAAAAB3n///ICQAAAAAAAAOc////nAcGBgYGDcj//+cdAAAAAAAAAAADnP////n5+fn5+v//+T4AAAAAAAAAAAAAA5z////////////+bAAAAAAAAAAAAAAAAAOU9/n5+fn5+feQAQAAAAAAAAAAAAAAAAAABQYGBgYGBgUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["fishing-rod"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARMBAAAAAAAAAAAAAAAAAAAAAAAAAAAFsf2uAQAAAAAAAAAAAAAAAAAAAAAAAAGU///9EwAAAAAAAAAAAAAAAAAAAAAAAGr+///pAgAAAAAAAAAAAAAAAAAAAAAARfr////mAQAAAAAAAAAAAAAAAAAAAAAo7f/////mAQAAAAAAAAAAAAAAAAAAABLX///68f/mAQAAAAAAAAAAAAAAAAAACrz///5r5v/mAQAAAAAAAAAAAAAAAAAKuf///5QC5v/mAQAAAAAAAAAAAAAAAAq5////tgUB5v/mAQAAAAAAAAAAAAAACrn///+5CgAB5v/mAQAAAAAAAAAAAAAKuf///7kKAAAB5v/mAQAAAAAAAAAAAAq5////uQoAAAAB5v/mAQAAAAAAAAAACrn///+5CgAAAAAD6P/mAQAAAAAAAAAKuf///7kKAAAAAA+u///iAQAAAAAAAAq5////uQoAAAAAKNX///xvAAAAAAAAAbP////7TQAAAABO7///704AAAAAAAAAE/3/////+4AEAG/8///VKAAAAAAAAAAAAa79zPv///+wAt3//64PAAAAAAAAAAAAAAETAkPm///9E2zdewIAAAAAAAAAAAAAAAAAAAAZuv2uAQABAAAAAAAAAAAAAAAAAAAAAAAAARMBAAAAAAAAAAAAAAAA",
    ["hand-heart"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5T1lAMAAAAAAAAAAAAAAAAAAAAAAAADnP///5wDAAAAAAAAAAAAAAAAAAAAAACU//////+UAAAAAAAAAAAAAAAAAAAAAAX3///Z///3BQAAAAAAAAAAAAAAAAAAAAb5//l1/f/5BgAAAAAAAAAAAAAAAAABAAb5//z8///9kBsAAAAAAAAAAAAAAHPdcwb3//////////VsAAAAAAAAAAAAev7//nuR////3PX1///sBAAAAAAAAAB6/v////7U///VDwQbxv/+MgAAAAAAAHP+//65/v///+8oAAAAcf//cQAAAAAAAd3//7kCev7//E4AAAAAMv7/sQAAAAAAAHP+//56AXPdbwAAAAAAev7/3QEAAAAAAAB6/v/+egEBAAAAAAB6/v/+cwAAAAAAAAAAev7//qlPCQAAAHr+//56AAAAAAAAAAAAAHr+////76RPev7//noAAAAAAAAAAAAAAABz7//////////+egAAAAAAAAAAAAAAAAAACU+k7/////56AAAAAAAAAAAAAAAAAAAAAAAACU+k3XMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["flame"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARMBAAAAAAAAAAAAAAAAAAAAAAAAAAABrv2zCgAAAAAAAAAAAAAAAAAAAAAAAAAW/v//uQoAAAAAAAAAAAAAAAAAAAAAAAAZ/v///7kKAAAAAAAAAAAAAAAAAAAAAAAZ/v////+5CgAAAAAAAAAAAAAAAAAAAAAZ/v//////uQoAAAAAAAAAAAAAAAAAAACA///+wf///7kKAAAAAAAAAAAAAAAAAEP7//+6DLn///+5CgAAAAAAAAAAAAAAGeb//+YZAFr8////swEAAAAAAAAAAAABuv//+5PDV9z//////iMAAAAAAAAAAAAW/v//gtz/+/7///7//1QAAAAAAAAAAAAZ/v/+Tf7//////////4cAAAAAAAAAAAAZ/v/+ov/++//7/////7sAAAAAAAAAAAAZ/v/+0//9q8Ov/////+sDAAAAAAAAAAAZ/v/+kPv/+8r7//////0TAAAAAAAAAAAW/v//+tv7/////////7MBAAAAAAAAAAABr//////9+/3/////uQoAAAAAAAAAAAAAAl7m//////////+5CgAAAAAAAAAAAAAAAAARkPr//////rMKAAAAAAAAAAAAAAAAAAAAADDB/diFMAEAAAAAAAAAAAAAAAAAAAAAAAABEwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["swords"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAE6D1jAAAAAAAAAAAAAOU9YwAAAAAAABO5f//9QQAAAAAAAAAA5z///UEAAAAAI7+///+jgAAAAAAAAADnP///5QAAAAABPX///lRAAAAAAAAAAOc////nAMAAAAAAJT///+cAwAAAAAAA5z///+cAwAAAAAAAAOc////nAMAAAADnP///5wDAAAAAAAAAAADnP///5wDAAOc////nAMAAAAAAAAAAAAAA5z///+cBpz///+cAwAAAAAAAAAAAAAAAAOc////2f///5wDAAAAAAAAAAAAAAAAAAADnP//////nAMAAAAAAAAAAAAAAAAAAAAABtn////ZBgAAAAAAAAAAAAAAAAAAAAADnP//////nAMAAAAAAAAAAAAAAAAAAAOc////2f///5wDAAAAAAAAAAAAAAAAA5z///+cBpz///+cAwAAAAAAAAAAAAADnP///5wDAAOc////nAMAAAAAAAAAAAOc////nAMAAAADnP///5wDAAAAAAAAAJT///+cAwAAAAAAA5z///+UAAAAAAAABPX//5wDAAAAAAAAAAOc///1BAAAAAAAAIz1lAMAAAAAAAAAAAADlPWMAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["shopping-bag"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFBgYGBgYGBgUAAAAAAAAAAAAAAAAAAIz3+fn5+fn5+feMAAAAAAAAAAAAAAAABff////////////3BQAAAAAAAAAAAAAFCvn//vn5+fn5/v/5CgUAAAAAAAAAAIz3+f7//vn5+fn5/v/++feMAAAAAAAABff////////////////////3BQAAAAAABvn//vn5+fn5+fn5+fn5/v/5BgAAAAAABvn/+QoGBgYGBgYGBgYK+f/5BgAAAAAABvn/+QYAAAAAAAAAAAAG+f/5BgAAAAAABvn/+QYAAAAAAAAAAAAG+f/5BgAAAAAABvn/+QYAAAAAAAAAAAAG+f/5BgAAAAAABvn/+QYAAAAAAAAAAAAG+f/5BgAAAAAABvn/+QYAAAAAAAAAAAAG+f/5BgAAAAAABvn/+QYAAAAAAAAAAAAG+f/5BgAAAAAABvn/+QYAAAAAAAAAAAAG+f/5BgAAAAAABvn/+QoGBgYGBgYGBgYK+f/5BgAAAAAABvn//vn5+fn5+fn5+fn5/v/5BgAAAAAABff////////////////////3BQAAAAAAAIz3+fn5+fn5+fn5+fn5+feMAAAAAAAAAAAFBgYGBgYGBgYGBgYGBgUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["shopping-cart"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUGBgUAAAAAAAAAAAAAAAAAAAAAAAAAjPf5+feMAAAAAAAAAAAAAAAAAAAAAAAE9f/////5DQAAAAAAAAAAAAAAAAAAAAAAjPf5/P//PgYGBgYGBgYGBgYFAAAAAAAAAAUGof//+vn5+fn5+fn5+fn3jAAAAAAAAAAAbv//////////////////9QQAAAAAAAAAO////fn5+fn5+fn5+v//xQAAAAAAAAAADfr/+hIGBgYGBgYGov//fQAAAAAAAAAAANP//zsAAAAAAAAE5v//NAAAAAAAAAAAAKH//24AAAAAAAA0///mBAAAAAAAAAAAAG7//6EGBgYGBgZ+//+hAAAAAAAAAAAAADv///z5+fn5+fn8//9YAAAAAAAAAAAAAA35//////////////oUAAAAAAAAAAAAAACM+f/++fn5+fv//o8AAAAAAAAAAAAAAAA4+v//tAYGPfr//7IAAAAAAAAAAAAAAAB7////9gUAe/////YFAAAAAAAAAAAAAAA4+v//sgAAOPr//7IAAAAAAAAAAAAAAAAAOH1qDAAAADh9agwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["store"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQYGBgYGBgYGBgYGBQAAAAAAAAAAAACM9/n5+fn5+fn5+fn594wAAAAAAAAAACH7//////////////////shAAAAAAAAAIT///v5+fn5+fn5+fn7//+EAAAAAAAABuP//1MGBgYGBgYGBgZT///jBgAAAAAAUf//4wwGBgYGBgYGBgYM4///UQAAAAAAtv///Pn5+fn5+fn5+fn5/P//tgAAAAAE9f//////////////////////9QQAAAAAjP3//vn5+fn5+fn5+fn5/v/9jAAAAAAABvn/+QoGBgYGCgYGBgYK+f/5BgAAAAAABvn/+QYAAACM9YwAAAAG+f/5BgAAAAAABvn/+QYAAAX3//cFAAAG+f/5BgAAAAAABvn/+QYAAAb5//kGAAAG+f/5BgAAAAAABvn/+QYAAAb5//kGAAAG+f/5BgAAAAAABvn/+QYAAAb5//kGAAAG+f/5BgAAAAAABvn/+QoGBgr5//kKBgYK+f/5BgAAAAAABvn//vn5+fn+//75+fn5/v/5BgAAAAAABff////////////////////3BQAAAAAAAIz3+fn5+fn5+fn5+fn5+feMAAAAAAAAAAAFBgYGBgYGBgYGBgYGBgUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["repeat-2"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUGBgYGBgYGBgYGBgUAAAAAAAAAAAAAjPf5+fn5+fn5+fn5+feMAAAAAAAAAAAE9f/////////////////3BQAAAAAAAAAAjPf5+fn5+fn5+fn5/v/5BgAAAAAAAAAToPWPBgYGBgYGBo/1/f/5BgAAAAAAAE7l///1BAAAAAAABPX////5BgAAAAAAjv7///6OAAAAAAAAAI7+///+jgAAAAAE9f///5MBAAAAAAAAAAGT////9QQAAAAAjv7///6OAAAAAAAAAI7+///+jgAAAAAABvn////1BAAAAAAABPX//+VOAAAAAAAABvn//fWPBgYGBgYGBo/1oBMAAAAAAAAABvn//vn5+fn5+fn5+fn3jAAAAAAAAAAABff/////////////////9QQAAAAAAAAAAIz3+fn5+fn5+fn5+fn3jAAAAAAAAAAAAAAFBgYGBgYGBgYGBgYFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["scroll-text"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQYGBgYGBgYGBgYGBQAAAAAAAAAAAACM9/n5+fn5+fn5+fn594wAAAAAAAAAAAX3//////////////////cFAAAAAAAAAAb5//75+fn5+fn5+fn+//kGAAAAAAAAAAb5//kKBgYGBgYGBgr5//kGAAAAAAAAAAb5//kGAAAAAAAAAAb5//kGAAAAAAAAAAb5//lXxsrKysrKxlf5//kGAAAAAAAAAAb5//nD/////////8P5//kGAAAAAAAAAAb5//lXxsrKysrKxlf5//kGAAAAAAAAAAb5//lXxsrKysrKxlf5//kGAAAAAAAAAAb5//nD/////////8P5//kGAAAAAAAAAAb5//lXxsrKysrKxlf5//kGAAAAAAAAAAb5//lXxsrKysZRAAb5//kGAAAAAAAAAAb5//nD///////DAAb5//kGAAAAAAAAAAb5//lXxsrKysZRAAb5//kGAAAAAAAAAAb5//kGAAAAAAAAAAb5//kGAAAAAAAAAAb5//kKBgYGBgYGBgr5//kGAAAAAAAAAAb5//75+fn5+fn5+fn+//kGAAAAAAAAAAX3//////////////////cFAAAAAAAAAACM9/n5+fn5+fn5+fn594wAAAAAAAAAAAAABQYGBgYGBgYGBgYGBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["trending-up"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQYGBhMBAAAAAAAAAAAAAAAAAAAAAACM9/n5+f2uAQAAAAAAAAAAAAAAAAAAAAT1///////9EwAAAAAAAAAAAAAAAAAAAACM9/r////5BgAAAAAAAAAAAAAAAAAAAAAACMD////5BgAAAAAAAAAAAAAAAAAAAAAAbP/////5BgAAAAAAAAAAAAAAARMBAAAk8v/////3BQAAAAAAAAAAAAAKs/2zCgO+///yoPWMAAAAAAAAAAAAAAq5////uXX///9sAAQAAAAAAAAAAAAACrn///////7//74DAAAAAAAAAAAAAAAKuf///+7/////8iQAAAAAAAAAAAAAAAq5////uRS5////bAAAAAAAAAAAAAAAAbP///+5CgAKs/2vAwAAAAAAAAAAAAAAE/3//7kKAAAAARMBAAAAAAAAAAAAAAAAAa79swoAAAAAAAAAAAAAAAAAAAAAAAAAAAETAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["map-pin"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHFwcAAAAAAAAAAAAAAAAAAAAAAAAAGKHz/vOhGAAAAAAAAAAAAAAAAAAAAAAY3v//////3hgAAAAAAAAAAAAAAAAAAACh/////v///6EAAAAAAAAAAAAAAAABEwjz//+TIpP///MIEwEAAAAAAAAAAAGu/bn+//4iACL+//65/a4BAAAAAAAAABP9///9//+TIpP///3///0TAAAAAAAAAAHB/////////v///////8EBAAAAAAAAAAAw+v///v///////v//+jAAAAAAAAAAAAAAkP///cbz/vPG/f//kAAAAAAAAAAAAAAAEeb//8EJFwnB///mEQAAAAAAAAAAAAAAAF7///9eAF7///9eAAAAAAAAAAAAAAAAAALB///mIeb//8ECAAAAAAAAAAAAAAAAAAAw+v//5f//+jAAAAAAAAAAAAAAAAAAAAAAkP//////kAAAAAAAAAAAAAAAAAAAAAAAEeb////mEQAAAAAAAAAAAAAAAAAAAAAAAF7///9eAAAAAAAAAAAAAAAAAAAAAAAAAAKv/a8CAAAAAAAAAAAAAAAAAAAAAAAAAAABEwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["ship"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjPWMAAAAAAAAAAAAAAAAAAAAAAAAAAAF9//4IgAAAAAAAAAAAAAAAAAAAAAAAAAG+f//9YMNAAAAAAAAAAAAAAAAAAAAAAAG+f/////jXwMAAAAAAAAAAAAAAAAAAAAG+f/9/////8k8AAAAAAAAAAAAAAAAAAAG+f/5Y+P////9jQAAAAAAAAAAAAAAAAAG+f/5Bg2D9f//9wUAAAAAAAAAAAQAAAAG+f/5BgAAI/r/+QYEAAAAAAAAjPWUAwAG+f/5BgAABvn/+Zf1jAAAAAAE9f//nAMF9//3BQAABff//f//9QQAAAAAlP///5wIj/WPBgYGBo/8////lAAAAAAAA5z////5+fn5+fn5+fn///+cAwAAAAAAAAOc/////////////////5wDAAAAAAAAAAADlPf5+fn5+fn5+fn3lAMAAAAAAAAAAAAAAAUGBgYGBgYGBgYFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["user"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARk/Sj8ZAQAAAAAAAAAAAAAAAAAAAAxw0v3////90nAMAAAAAAAAAAAAAAAAQuD////////////gQgAAAAAAAAAAAABe+v//6cPg7eDD6f//+l4AAAAAAAAAAEL6//yFd/v////7d4X8//pCAAAAAAAADOD//Fky+///////+zJZ/P/gDAAAAAAAcP//hQCR///HVMf//5EAhf//cAAAAAAB0v/pDACy//9UAFT//7IADOn/0gEAAAAZ/f+WAACR///HVMf//5EAAJb//RkAAAA///9gAAAy+///////+zIAAGD//z8AAABK//9MAAAAbPv////7bAAAAEz//0oAAAA///9gAAADNKX7//ulNAMAAGD//z8AAAAZ/f+WACjg/////////+AoAJb//RkAAAAB0v/pDKz//////v////+sDOn/0gEAAAAAcP//qPz//KFYI1ih/P/8qP//cAAAAAAADOD/////rAAAAAAArP/////gDAAAAAAAAEL6///9OgAAAAAAOv3///pCAAAAAAAAAABe+v//6ZZgTGCW6f//+l4AAAAAAAAAAAAAQuD////////////gQgAAAAAAAAAAAAAAAAxw0v3////90nAMAAAAAAAAAAAAAAAAAAAAARk/Sj8ZAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["user-round"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARk/Sj8ZAQAAAAAAAAAAAAAAAAAAAAxw0v3////90nAMAAAAAAAAAAAAAAAAQuD////////////gQgAAAAAAAAAAAABe+v//6cPg7eDD6f//+l4AAAAAAAAAAEL6//yFd/v////7d4X8//pCAAAAAAAADOD//Fky+///////+zJZ/P/gDAAAAAAAcP//hQCR///HVMf//5EAhf//cAAAAAAB0v/pDACy//9UAFT//7IADOn/0gEAAAAZ/f+WAACR///HVMf//5EAAJb//RkAAAA///9gAAAy+///////+zIAAGD//z8AAABK//9MAAAAbPv////7bAAAAEz//0oAAAA///9gAAADNKX7//ulNAMAAGD//z8AAAAZ/f+WACjg/////////+AoAJb//RkAAAAB0v/pDKz//////v////+sDOn/0gEAAAAAcP//qPz//KFYI1ih/P/8qP//cAAAAAAADOD/////rAAAAAAArP/////gDAAAAAAAAEL6///9OgAAAAAAOv3///pCAAAAAAAAAABe+v//6ZZgTGCW6f//+l4AAAAAAAAAAAAAQuD////////////gQgAAAAAAAAAAAAAAAAxw0v3////90nAMAAAAAAAAAAAAAAAAAAAAARk/Sj8ZAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["users-round"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQmRCBAAAAAAAAAAAAAAAAARCZEIEACLQ////0CIAAAAAAAAAAAAAItD////QJtD//////9AEAAAAAAAAAAAE0P//////6f//rjyu//9CAAAAAAAAAABC//+uPK7/////PAA8//9kAAAAAAAAAABk//88ADz/////rjyu//9CAAAAAAAAAABC//+uPK7//+n//////9AEAAAAAAAAAAAE0P//////0CbQ////0CIAAAAAAAAAAAAAI9/////QIgANkOn1khsAAAAAAAAAAAAXyP7////1bGzv//////VsAAAAAAAAAACQ/////v//7+/////9///vCQAAAAAAABv1//VoJ7z/////x08hvP//TwAAAAAAAJD//5AAAE//////TwAAT///pAAAAAAAAd3/9RsAAAnv///vCQAACe//3QEAAAAAAGzdbAAAAABs3d1sAAAAAGzdbAAAAAAAAAABAAAAAAAAAQEAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["lock"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARYZGRkWAQAAAAAAAAAAAAAAAAAAAAAKs/7+/v7+swoAAAAAAAAAAAAAAAAAAAq5/////////7kKAAAAAAAAAAAAAAAAAbP////+/v7///+zAQAAAAAAAAAAAAAAFv7//7kcGRy5///+FgAAAAAAAAAAAAAAGf7//hwAAAAc/v/+GQAAAAAAAAAAAAABKf7//iwZGRks/v/+KQEAAAAAAAAAAAGu/v////7+/v7+/////q4BAAAAAAAAABb+//////////////////4WAAAAAAAAABn+///+/v7+/v7+/v7///4ZAAAAAAAAABn+//4sGRkZGRkZGSz+//4ZAAAAAAAAABn+//4ZAAAAAAAAABn+//4ZAAAAAAAAABn+//4ZAAAAAAAAABn+//4ZAAAAAAAAABn+//4ZAAAAAAAAABn+//4ZAAAAAAAAABn+//4ZAAAAAAAAABn+//4ZAAAAAAAAABn+//4ZAAAAAAAAABn+//4ZAAAAAAAAABn+//4sGRkZGRkZGSz+//4ZAAAAAAAAABn+///+/v7+/v7+/v7///4ZAAAAAAAAABb+//////////////////4WAAAAAAAAAAGu/v7+/v7+/v7+/v7+/q4BAAAAAAAAAAABFhkZGRkZGRkZGRkZFgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["shield-alert"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEwEAAAAAAAAAAAAAAAAAAAAAAAAACmLO/c5iCgAAAAAAAAAAAAAAAAAAAB+G6f//////6YYfAAAAAAAAAAAAAAE+qvr////////////6qj4BAAAAAAAAAa7+//////qqWKr6//////6uAQAAAAAAFP3////phh8ABAAfhun////9FAAAAAAABvb//4AKAACM9YwAAAqA///2BgAAAAAAAdv//1wAAAX3//cFAABc///bAQAAAAAAALz//30AAAb5//kGAAB9//+8AAAAAAAAAJz//5wAAAb5//kGAACc//+cAAAAAAAAAH3//7wAAAb5//kGAAC8//99AAAAAAAAAFz//9sBAAb5//kGAAHb//9cAAAAAAAAAD3///YHAAb5//kGAAf2//89AAAAAAAAAB3+//+MAAX3//cFAIz///4dAAAAAAAAAAG4///+WgCM9YwAWv7//7gBAAAAAAAAAAAU3f//9DEABAAx9P//3RQAAAAAAAAAAAAAMfT//90UABTd///0MQAAAAAAAAAAAAAAAFr+//++FL7///5aAAAAAAAAAAAAAAAAAACM////7v///4wAAAAAAAAAAAAAAAAAAAAFtv//////tgUAAAAAAAAAAAAAAAAAAAAACrn///+5CgAAAAAAAAAAAAAAAAAAAAAAAAqz/bMKAAAAAAAAAAAAAAAAAAAAAAAAAAABEwEAAAAAAAAAAAAA",
    ["shield"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEwEAAAAAAAAAAAAAAAAAAAAAAAAACmLO/c5iCgAAAAAAAAAAAAAAAAAAAB+G6f//////6YYfAAAAAAAAAAAAAAE+qvr////////////6qj4BAAAAAAAAAa7+//////qqWKr6//////6uAQAAAAAAFP3////phh8ABAAfhun////9FAAAAAAABvb//4AKAACM9YwAAAqA///2BgAAAAAAAdv//1wAAAX3//cFAABc///bAQAAAAAAALz//30AAAb5//kGAAB9//+8AAAAAAAAAJz//5wAAAb5//kGAACc//+cAAAAAAAAAH3//7wAAAb5//kGAAC8//99AAAAAAAAAFz//9sBAAb5//kGAAHb//9cAAAAAAAAAD3///YHAAb5//kGAAf2//89AAAAAAAAAB3+//+MAAX3//cFAIz///4dAAAAAAAAAAG4///+WgCM9YwAWv7//7gBAAAAAAAAAAAU3f//9DEABAAx9P//3RQAAAAAAAAAAAAAMfT//90UABTd///0MQAAAAAAAAAAAAAAAFr+//++FL7///5aAAAAAAAAAAAAAAAAAACM////7v///4wAAAAAAAAAAAAAAAAAAAAFtv//////tgUAAAAAAAAAAAAAAAAAAAAACrn///+5CgAAAAAAAAAAAAAAAAAAAAAAAAqz/bMKAAAAAAAAAAAAAAAAAAAAAAAAAAABEwEAAAAAAAAAAAAA",
    ["eye-off"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAETAQAAAAAAAAAAAAAAAAAAAAAAAAAAAa79swoAAAAAAAAAAAAAAAAAAAAAAAAAE/3//7kKAAAABAAAAAAAAAAAAAAAAAAAAbP///+5TIvL9cuLTBEAAAAAAAAAAAAAAAq5//////////////qUAwAAAAAAAAAAAAAN4////////v//////nAMAAAAAAAAAAAOc///////aJkyLz////5wDAAAAAAAAA5z////j////uQoAA5z///+cAwAAAAAAlP///5wNuf///7kKAAOc////lAAAAAAE9f//2QYACrn///+5CgAG2f//9QQAAAAAlP///5wDAAq5////uQ2c////lAAAAAAAA5z///+cAwAKuf///+P///+cAwAAAAAAAAOc////z4tMJtr//////5wDAAAAAAAAAAADnP///////v//////4w0AAAAAAAAAAAAAA5T6/////////////7kKAAAAAAAAAAAAAAARTIvL9cuLTLn///+zAQAAAAAAAAAAAAAAAAAABAAAAAq5///9EwAAAAAAAAAAAAAAAAAAAAAAAAAKs/2uAQAAAAAAAAAAAAAAAAAAAAAAAAAAARMBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["copy"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUGBgYGBgYGBgYGBQAAAAAAAAAAAAAAjPf5+fn5+fn5+fn594wAAAAAAAAAAAAF9/////////////////cFAAAAAAAAAAAG+f/++fn5+fn5+fn+//kKBgUAAAAAAAAG+f/5C4/3+fn5+fn+//75+feMAAAAAAAG+f/5C/f////////////////3BQAAAAAG+f/5DPn//vn5+fn+//75/v/5BgAAAAAG+f/5DPn/+QoGBgr5//kP+f/5BgAAAAAG+f/5DPn/+QYAAAb5//kM+f/5BgAAAAAG+f/5DPn/+QYAAAb5//kM+f/5BgAAAAAG+f/5DPn/+QYAAAb5//kM+f/5BgAAAAAG+f/5DPn/+QYAAAb5//kM+f/5BgAAAAAG+f/5D/n/+QoGBgr5//kM+f/5BgAAAAAG+f/++f7//vn5+fn+//kM+f/5BgAAAAAF9/////////////////cL+f/5BgAAAAAAjPf5+f7//vn5+fn5948L+f/5BgAAAAAAAAUGCvn//vn5+fn5+fn5/v/5BgAAAAAAAAAABff////////////////3BQAAAAAAAAAAAIz3+fn5+fn5+fn5+feMAAAAAAAAAAAAAAAFBgYGBgYGBgYGBgUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["external-link"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUGBgYGBgYFAAAAAAAAAAAAAAAAAAAAjPf5+fn5+fn3jAAAAAAAAAAAAAAAAAAE9f//////////9wUAAAAAAAUGBgYGBgYGj/f5+fn9////+QYAAAAAjPf5+fn5+fn5+fn5+fn/////+QYAAAAF9/////////////////////3/+QYAAAAG+f/++fn5+fn5+fn9////+fn/+QYAAAAG+f/5CgYGBgYGCZ//////+fn/+QYAAAAG+f/5BgAAAAADnP////3/+fn/+QYAAAAG+f/5BgAAAAOc////n/n/+ff/9wUAAAAG+f/5BgAAA5z///+cCfn/+Y/1jAAAAAAG+f/5BgAAlP///5wDBvn/+QYEAAAAAAAG+f/5BgAE9f//nAMABvn/+QYAAAAAAAAG+f/5BgAAjPWUAwAABvn/+QYAAAAAAAAG+f/5BgAAAAQAAAAABvn/+QYAAAAAAAAG+f/5BgAAAAAAAAAABvn/+QYAAAAAAAAG+f/5CgYGBgYGBgYGCvn/+QYAAAAAAAAG+f/++fn5+fn5+fn5+f7/+QYAAAAAAAAF9///////////////////9wUAAAAAAAAAjPf5+fn5+fn5+fn5+fn3jAAAAAAAAAAAAAUGBgYGBgYGBgYGBgYFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["message-circle"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKRXJ+ckUKAAAAAAAAAAAAAAAAAAAAFI7v///////vjhQAAAAAAAAAAAAAAAA95f///////////+U9AAAAAAAAAAAAAD30////15aBltf////0PQAAAAAAAAAAFOX//+dQAgAAAAJQ5///5RQAAAAAAAAAjv//5yQAAAAAAAAAJOf//44AAAAAAAAK7///UAAAAAAAAAAAAFD//+8KAAAAAABF///XAgAAAAAAAAAAAALX//9FAAAAAABy//+WAAAAAAAAAAAAAACW//9yAAAAAAB+//+BAAAAAAAAAAAAAACB//9+AAAAAABy//+WAAAAAAAAAAAAAACW//9yAAAAAABF///XAgAAAAAAAAAAAALX//9FAAAAAAAK7///UAAAAAAAAAAAAFD//+8KAAAAAAAAjv//5yQAAAAAAAAAJOf//44AAAAAAAAAFOX//+dQBQAAAAJQ5///5RQAAAAAAAAAAEv/////9qqBltf////0PQAAAAAAAAAAAGn//////////////+U9AAAAAAAAAAAAAL7////////////vjhQAAAAAAAAAAAAABPX///ysUHJ+ckUKAAAAAAAAAAAAAAAAAIz1rDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["music-2"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0vBgAAAAAAAAAAAAAAAAAAAAAGPG+i1Pr/zAYAAAAAAAAAAAAAAAAAAAbM/////////zIAAAAAAAAAAAAAAAAAADL//////////zUAAAAAAAAAAAAAAAAAADX////WuP///zUAAAAAAAAAAAAAAAAAADX///81Nf///zUAAAAAAAAAAAAAAAAAADX///81Nf///zUAAAAAAAAAAAAAAAAAADX///81Nf///zUAAAAAAAAAAAAAAAAAADX///81Nf///zUAAAAAAAAAAAAAAAAAADb////fpv///zUAAAAAAAAAAAAAAAEFDcn//////////zUAAAAAAAAAAAAMhN/47P///////////zUAAAAAAAAAAAzJ//////////+e/////zIAAAAAAAAAAIT////7//////8/+///zAYAAAAAAAAAAd///3ML3/////+b///fBwAAAAAAAAAABfj/+woAhP////7///+EAAAAAAAAAAAAAd///3MKdP///////8kMAAAAAAAAAAAAAIT////7////7PjfhAwAAAAAAAAAAAAAAAzJ///////JDQUBAAAAAAAAAAAAAAAAAAAMhN/434QMAAAAAAAAAAAAAAAAAAAAAAAAAAEFAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["sparkles"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABs3WwAAAAAAAAAAAAAAAAAAAAAAAAAAAHi/+IBAAAAAAAAAAAAAAAAAAAAAAAAAAHm/+YBAAAAAAAAAAAAAAAAAAAAAAABAQLm/+YCAQEAAAAAAAAAAAAAAAAAAGzi5ub4//jm5uJsAAAAAAAAAAAAAAAAAd3////////////dAQAAAAAAAAAAAAAAAGzi5ub4//jm5uJsAAAAAAAAAAAAAAAAAAABAQLm/+YCAQEAAAAAAAAAAAAAAAAAAAAAAAHm/+YBAAAAAAAAAAAAAAAAAAAAAAAAAAHi/+IBAAAAOKs4AAAAAAAAAAAAAAAAAABs3WwAAAAAsP+wAAAAAAAAAAA4qzgAAAAAAQAAAAMxwf/BMQMAAAAAAACw/7AAAAAAAAAAAIv//////4sAAAAAAAC0/7QAAAAAAAAAAIv//////4sAAAA4sLTm/+a0sDgAAAAAAAMxwf/BMQMAAACr/////////6sAAAAAAAAAsP+wAAAAAAA4sLTm/+a0sDgAAAAAAAAAOKs4AAAAAAAAAAC0/7QAAAAAAAAAAAAAAAAAAAAAAAAAAACw/7AAAAAAAAAAAAAAAAAAAAAAAAAAAAA4qzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["shapes"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIGAgAAAAAAAAQAAAAAAAAAAAAAAAAlneX45Z0lAAADlPWUAwAAAAAAAAAAAEzz///////zTAOc////nAMAAAAAAAAAJfP///76/v//86r//////5wDAAAAAAAAnf//2jsIO9r//////9n///+cAwAAAAAC5f/+OwAAADv+////nAac////lAAAAAAG+P/6CAAAAAj6///ZBgAG2f//9QQAAAAC5f/+OwAAADv+////nAac////lAAAAAAAnf//2jsIO9r//////9n///+eAwAAAAAAJfP///76/v////7///////33jAAAAAAAAEzz////////////////////9wUAAAAAAAAlneX45Z/6//75+fn5+f7/+QYAAAAAAAAAAAIGAgb5//kKBgYGCvn/+QYAAAAAAAAAAAAAAAb5//kGAAAABvn/+QYAAAAAAAAAAAAAAAb5//kGAAAABvn/+QYAAAAAAAAAAAAAAAb5//kGAAAABvn/+QYAAAAAAAAAAAAAAAb5//kKBgYGCvn/+QYAAAAAAAAAAAAAAAb5//75+fn5+f7/+QYAAAAAAAAAAAAAAAX3////////////9wUAAAAAAAAAAAAAAACM9/n5+fn5+fn3jAAAAAAAAAAAAAAAAAAABQYGBgYGBgYFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ["zap"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY71jAAAAAAAAAAAAAAAAAAAAAAAAAAAVf7/9QQAAAAAAAAAAAAAAAAAAAAAAAAc6///ywAAAAAAAAAAAAAAAAAAAAAAAAK4////iwAAAAAAAAAAAAAAAAAAAAAAAG7/////TAAAAAAAAAAAAAAAAAAAAAAALPX////6EQAAAAAAAAAAAAAAAAAAAAAHzf/////LAAAAAAAAAAAAAAAAAAAAAACH//////+OBgYFAAAAAAAAAAAAAAAAAD/7///3///6+fn3jAAAAAAAAAAAAAAAEN7//7v1////////9QQAAAAAAAAAAAAAnv////n9//35////ngAAAAAAAAAAAAAE9f////////W7///eEAAAAAAAAAAAAAAAjPf5+fr///f///s/AAAAAAAAAAAAAAAAAAUGBo7//////4cAAAAAAAAAAAAAAAAAAAAAAMv/////zQcAAAAAAAAAAAAAAAAAAAAAEfr////1LAAAAAAAAAAAAAAAAAAAAAAATP////9uAAAAAAAAAAAAAAAAAAAAAAAAi////7gCAAAAAAAAAAAAAAAAAAAAAAAAy///6xwAAAAAAAAAAAAAAAAAAAAAAAAE9f/+VQAAAAAAAAAAAAAAAAAAAAAAAAAAjPWOAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAA",
    ["volleyball"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADBgMAAAAAAAAAAAAAAAAAAAAAAAAigsfv+O/HgiIAAAAAAAAAAAAAAAAADJH5//////////mRDAAAAAAAAAAAAAAZzv////jNvM34////zhkAAAAAAAAAAAzO///scBMAAAATcOz//84MAAAAAAAAAJH//9QfAAAAAAAAAB/U//+RAAAAAAAAIvn/7SAAAAAAAAAAAAAg7f/5IgAAAAAAgv//cAAAAAAAAAAAAAAAcP//ggAAAAAAx//4EAAAAAAAAAAAAAAAEPj/xwAAAAAD7//OAAAAAAAAAAAAAAAAAM7/7wMAAAAG+P++AAAAAAAAAAAAAAAAAL7/+AYAAAAD7//OAAAAAAAAAAAAAAAAAM7/7wMAAAAAx//4EAAAAAAAAAAAAAAAEPj/xwAAAAAAgv//cAAAAAAAAAAAAAAAcP//ggAAAAAAIvn/7SAAAAAAAAAAAAAg7f/5IgAAAAAAAJH//9QfAAAAAAAAAB/U//+RAAAAAAAAAAzO///scBMAAAATcOz//84MAAAAAAAAAAAZzv////jNvM34////zhkAAAAAAAAAAAAADJH5//////////mRDAAAAAAAAAAAAAAAAAAigsfv+O/HgiIAAAAAAAAAAAAAAAAAAAAAAAADBgMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
}

local PACK_ALIASES = {
    dashboard="layout-dashboard", layout="layout-dashboard", overview="layout-dashboard", home="house",
    config="panel-left", tune="panel-left", close="x", remove="minus", add="plus", next="chevron-right",
    expand="chevron-down", cancel="x", back="chevron-right", warning="shield-alert", success="circle-check",
    player="user-round", players="users-round", settings="settings", update="history", discord="message-circle",
}

local B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
local function decodePacked(value)
    local out = {}
    local acc = 0
    local bits = 0
    for i = 1, #value do
        local c = value:sub(i, i)
        if c ~= "=" then
            local pos = B64:find(c, 1, true)
            if pos then
                acc = acc * 64 + (pos - 1)
                bits = bits + 6
                while bits >= 8 do
                    bits = bits - 8
                    local byte = math.floor(acc / (2 ^ bits)) % 256
                    out[#out + 1] = string.char(byte)
                    acc = acc % (2 ^ bits)
                end
            end
        end
    end
    return table.concat(out)
end

local function normalizeIconName(name)
    local key = string.lower(tostring(name or "circle")):gsub("%s+", "-")
    return PACK_ALIASES[key] or key
end

local function fallbackPixelIcon(parent, name, position, size, color, z)
    local holder = make("Frame", {
        Name = "PackedPixelFallback", BackgroundTransparency = 1, BorderSizePixel = 0,
        Position = position or UDim2.fromOffset(0, 0), Size = size or UDim2.fromOffset(20, 20),
        ZIndex = z or 5,
    }, parent)
    local data = decodePacked(PACKED_ICONS[normalizeIconName(name)] or PACKED_ICONS["circle-check"] or "")
    if #data < 576 then return holder end

    -- Lightweight raster fallback: compress each bitmap row into contiguous alpha runs.
    -- This preserves anti-aliased alpha without creating a 24x24 Frame grid.
    for y = 0, 23 do
        local x = 0
        while x < 24 do
            local a = string.byte(data, y * 24 + x + 1) or 0
            if a > 10 then
                local startX = x
                local sum = a
                local count = 1
                x = x + 1
                while x < 24 do
                    local nextA = string.byte(data, y * 24 + x + 1) or 0
                    if nextA <= 10 then break end
                    sum = sum + nextA
                    count = count + 1
                    x = x + 1
                end
                local avg = sum / count
                local alphaTransparency = 1 - math.clamp(avg / 255, 0, 1)
                local pixel = make("Frame", {
                    BackgroundColor3 = color or C.muted,
                    BackgroundTransparency = alphaTransparency,
                    BorderSizePixel = 0,
                    Position = UDim2.new(startX / 24, 0, y / 24, 0),
                    Size = UDim2.new(count / 24, 0, 1 / 24, 0),
                    ZIndex = z or 5,
                }, holder)
                pixel:SetAttribute("KhfreshOriginalTransparency", alphaTransparency)
            else
                x = x + 1
            end
        end
    end
    return holder
end

local function packedIcon(parent, name, position, size, color, z)
    local holder = make("Frame", {
        Name = "PackedIcon_" .. safeName(name), BackgroundTransparency = 1, BorderSizePixel = 0,
        Position = position or UDim2.fromOffset(0, 0), Size = size or UDim2.fromOffset(20, 20),
        ZIndex = z or 5,
    }, parent)
    local packed = PACKED_ICONS[normalizeIconName(name)]
    if not packed then
        pcall(function() holder:Destroy() end)
        return fallbackPixelIcon(parent, "circle", position, size, color, z)
    end

    local decoded = decodePacked(packed)
    local usedEditable = false
    local bufferAvailable, rawBuffer = pcall(function() return buffer.create(24 * 24 * 4) end)
    if bufferAvailable and rawBuffer then
        local ok, editable = pcall(function()
            return AssetService:CreateEditableImage({Size = Vector2.new(24, 24)})
        end)
        if ok and editable then
            local buf = rawBuffer
            for i = 1, 576 do
                local a = string.byte(decoded, i) or 0
                local o = (i - 1) * 4
                buffer.writeu8(buf, o, 255)
                buffer.writeu8(buf, o + 1, 255)
                buffer.writeu8(buf, o + 2, 255)
                buffer.writeu8(buf, o + 3, a)
            end
            local wrote = pcall(function()
                editable:WritePixelsBuffer(Vector2.zero, Vector2.new(24, 24), buf)
            end)
            local contentValue = nil
            if wrote then
                pcall(function()
                    local contentType = rawget(_G, "Content")
                    if contentType and type(contentType.fromObject) == "function" then
                        contentValue = contentType.fromObject(editable)
                    end
                end)
            end
            if contentValue ~= nil then
                local image = make("ImageLabel", {
                    Name = "PackedBitmap", BackgroundTransparency = 1, BorderSizePixel = 0,
                    Size = UDim2.fromScale(1, 1), ImageContent = contentValue,
                    ImageColor3 = color or C.muted, ScaleType = Enum.ScaleType.Fit, ZIndex = z or 5,
                }, holder)
                table.insert(UI._iconImages, editable)
                usedEditable = image ~= nil
            else
                pcall(function() editable:Destroy() end)
            end
        end
    end
    if not usedEditable then
        holder:Destroy()
        return fallbackPixelIcon(parent, name, position, size, color, z)
    end
    return holder
end

local function iconSetColor(icon, color)
    if not icon then return end
    local image = icon:FindFirstChild("PackedBitmap")
    if image and image:IsA("ImageLabel") then
        image.ImageColor3 = color
    else
        for _, obj in ipairs(icon:GetDescendants()) do
            if obj:IsA("Frame") and obj ~= icon then obj.BackgroundColor3 = color end
        end
    end
end

-- ============================================================
-- WINDOW / TAB / SECTION
-- ============================================================
local Window = {}
Window.__index = Window
local Tab = {}
Tab.__index = Tab
local Section = {}
Section.__index = Section

local function updateSectionHeight(section)
    if not section or not section._frame or not section._body or not section._layout then return end
    local bodyH = section._layout.AbsoluteContentSize.Y
    section._body.Size = UDim2.new(1, 0, 0, bodyH)
    section._frame.Size = UDim2.new(1, 0, 0, 45 + bodyH + 12)
end

local function updateColumnHeight(column, layout)
    if not column or not layout then return end
    column.Size = UDim2.new(column.Size.X.Scale, column.Size.X.Offset, 0, layout.AbsoluteContentSize.Y)
end

local function buildSectionHost(tab)
    tab._headerHost = make("Frame", {
        Name = "HeaderHost", BackgroundTransparency = 1, BorderSizePixel = 0,
        Size = UDim2.new(1, 0, 0, 0), AutomaticSize = Enum.AutomaticSize.Y,
    }, tab._page)
    tab._headerLayout = list(tab._headerHost, 5)
    tab._headerHost.LayoutOrder = 1

    if tab._settingsBento then
        tab._grid = make("Frame", {
            Name = "BentoGrid", BackgroundTransparency = 1, BorderSizePixel = 0,
            Size = UDim2.new(1, 0, 0, 0), AutomaticSize = Enum.AutomaticSize.Y, LayoutOrder = 2,
        }, tab._page)
        tab._left = make("Frame", {
            Name = "LeftColumn", BackgroundTransparency = 1, BorderSizePixel = 0,
            Size = UDim2.new(0.5, -6, 0, 0),
        }, tab._grid)
        tab._right = make("Frame", {
            Name = "RightColumn", BackgroundTransparency = 1, BorderSizePixel = 0,
            Size = UDim2.new(0.5, -6, 0, 0), Position = UDim2.new(0.5, 6, 0, 0),
        }, tab._grid)
        tab._leftLayout = list(tab._left, 10)
        tab._rightLayout = list(tab._right, 10)
        tab._settingsLeftConn = tab._leftLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
            updateColumnHeight(tab._left, tab._leftLayout)
            updateColumnHeight(tab._right, tab._rightLayout)
            local h = math.max(tab._leftLayout.AbsoluteContentSize.Y, tab._rightLayout.AbsoluteContentSize.Y)
            tab._grid.Size = UDim2.new(1, 0, 0, h)
        end)
        tab._settingsRightConn = tab._rightLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
            updateColumnHeight(tab._left, tab._leftLayout)
            updateColumnHeight(tab._right, tab._rightLayout)
            local h = math.max(tab._leftLayout.AbsoluteContentSize.Y, tab._rightLayout.AbsoluteContentSize.Y)
            tab._grid.Size = UDim2.new(1, 0, 0, h)
        end)
        return tab._grid
    end

    tab._listHost = make("Frame", {
        Name = "ElementHost", BackgroundTransparency = 1, BorderSizePixel = 0,
        Size = UDim2.new(1, 0, 0, 0), AutomaticSize = Enum.AutomaticSize.Y, LayoutOrder = 2,
    }, tab._page)
    tab._elementLayout = list(tab._listHost, 10)
    return tab._listHost
end

function UI:SetTheme(name)
    applyTheme(name)
    for _, win in ipairs(UI._windows) do
        if win.ApplyTheme then pcall(function() win:ApplyTheme() end) end
    end
end
function UI:GetTheme() return currentTheme end
function UI:GetThemes() return {"Bento", "Dark"} end

function UI:Notify(config)
    config = config or {}
    if not self._notifyGui or not self._notifyGui.Parent then
        self._notifyGui = make("ScreenGui", {
            Name = "KhfreshNotify", ResetOnSpawn = false, IgnoreGuiInset = true,
            DisplayOrder = 2147483640, ZIndexBehavior = Enum.ZIndexBehavior.Global,
        }, GuiParent)
        local wrap = make("Frame", {Name = "Wrapper", BackgroundTransparency = 1, Size = UDim2.fromScale(1, 1)}, self._notifyGui)
        local lay = list(wrap, 8)
        lay.HorizontalAlignment = Enum.HorizontalAlignment.Right
        lay.VerticalAlignment = Enum.VerticalAlignment.Bottom
        pad(wrap, 0, 16, 0, 16)
    end
    local wrap = self._notifyGui.Wrapper
    local mobile = isMobile()
    local card = make("Frame", {
        BackgroundColor3 = C.shell, BorderSizePixel = 0,
        Size = UDim2.fromOffset(mobile and 270 or 320, 72), LayoutOrder = -math.floor(os.clock() * 1000),
    }, wrap)
    corner(card, 16); outline(card, C.line, 0.2, 1)
    packedIcon(card, config.Icon or "info", UDim2.fromOffset(14, 18), UDim2.fromOffset(26, 26), C.accent, 5)
    local t = text(card, config.Title or "Khfresh", 13, C.text, true)
    t.Position = UDim2.fromOffset(50, 9); t.Size = UDim2.new(1, -60, 0, 20)
    local d = text(card, config.Content or config.Message or "", 11, C.secondary, false)
    d.Position = UDim2.fromOffset(50, 31); d.Size = UDim2.new(1, -60, 0, 32); d.TextWrapped = true
    task.delay(tonumber(config.Duration) or 3, function()
        if card.Parent then
            tween(card, Motion.fast, {BackgroundTransparency = 1})
            task.wait(0.12)
            pcall(function() card:Destroy() end)
        end
    end)
end

local function clampWindowSize(requested)
    local vp = getViewport()
    local mobile = isMobile()
    local minW = mobile and 292 or 540
    local minH = mobile and 350 or 430
    local maxW = math.max(minW, vp.X - (mobile and 10 or 28))
    local maxH = math.max(minH, vp.Y - (mobile and 10 or 28))
    local w = requested and requested.X.Offset or 760
    local h = requested and requested.Y.Offset or 540
    if mobile then
        w = math.min(maxW, math.max(minW, w))
        h = math.min(maxH, math.max(minH, h))
    else
        w = math.min(maxW, math.max(minW, w))
        h = math.min(maxH, math.max(minH, h))
    end
    return UDim2.fromOffset(w, h)
end

local function installMove(win)
    local shell = win._shell
    local handle = win._dragHandle
    local dragging = false
    local startInput = nil
    local startPos = nil

    local function begin(input)
        if input.UserInputType ~= Enum.UserInputType.MouseButton1 and input.UserInputType ~= Enum.UserInputType.Touch then return end
        dragging = true
        startInput = input.Position
        startPos = shell.Position
        win._moving = true
    end
    local function endMove(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
            dragging = false
            win._moving = false
        end
    end
    handle.InputBegan:Connect(begin)
    table.insert(win._connections, UserInputService.InputEnded:Connect(endMove))
    table.insert(win._connections, UserInputService.InputChanged:Connect(function(input)
        if not dragging then return end
        if input.UserInputType ~= Enum.UserInputType.MouseMovement and input.UserInputType ~= Enum.UserInputType.Touch then return end
        local delta = input.Position - startInput
        shell.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
    end))
end

local function installResize(win)
    local shell = win._shell
    local grip = win._resizeHandle
    local resizing = false
    local startInput, startSize = nil, nil
    grip.InputBegan:Connect(function(input)
        if input.UserInputType ~= Enum.UserInputType.MouseButton1 and input.UserInputType ~= Enum.UserInputType.Touch then return end
        resizing = true
        startInput = input.Position
        startSize = shell.AbsoluteSize
    end)
    table.insert(win._connections, UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then resizing = false end
    end))
    table.insert(win._connections, UserInputService.InputChanged:Connect(function(input)
        if not resizing then return end
        if input.UserInputType ~= Enum.UserInputType.MouseMovement and input.UserInputType ~= Enum.UserInputType.Touch then return end
        local d = input.Position - startInput
        local vp = getViewport()
        local mobile = isMobile()
        local minW = mobile and 292 or 540
        local minH = mobile and 350 or 430
        local maxW = math.max(minW, vp.X - (mobile and 8 or 20))
        local maxH = math.max(minH, vp.Y - (mobile and 8 or 20))
        local w = math.clamp(startSize.X + d.X, minW, maxW)
        local h = math.clamp(startSize.Y + d.Y, minH, maxH)
        shell.Size = UDim2.fromOffset(w, h)
        win._manualSize = shell.Size
        win:_refreshLayout()
    end))
end

function Window:_refreshLayout()
    local mobile = isMobile()
    self._mobile = mobile
    local topH = mobile and 68 or 82
    self._top.Size = UDim2.new(1, 0, 0, topH)
    self._rail.Position = UDim2.fromOffset(0, topH)
    self._rail.Size = UDim2.new(0, mobile and 64 or self._railWidth, 1, -topH)
    self._content.Position = UDim2.fromOffset(mobile and 64 or self._railWidth, topH)
    self._content.Size = UDim2.new(1, -(mobile and 64 or self._railWidth), 1, -topH)
    self._dragHandle.Position = UDim2.new(0.5, -80, 1, -20)
    self._dragHandle.Size = UDim2.fromOffset(190, 20)
    self._logoHolder.Size = UDim2.fromOffset(mobile and 46 or 54, mobile and 46 or 54)
    self._logoHolder.Position = UDim2.fromOffset(12, mobile and 9 or 14)
    if self._logo then
        self._logo.Size = UDim2.fromScale(1, 1)
    end
    self._brandText.Visible = not mobile
    self._authorText.Visible = not mobile
    self._minBtn.Position = UDim2.new(1, mobile and -84 or -86, 0, mobile and 17 or 24)
    self._closeBtn.Position = UDim2.new(1, mobile and -44 or -44, 0, mobile and 17 or 24)
    for _, tab in ipairs(self._tabs) do
        tab._label.Visible = not mobile
        tab._btn.Size = UDim2.new(1, 0, 0, mobile and 46 or 48)
        if mobile then
            tab._icon.Position = UDim2.new(0.5, -12, 0.5, -12)
        else
            tab._icon.Position = UDim2.fromOffset(12, 12)
        end
    end
    if self._settingsTab then
        local tab = self._settingsTab
        local width = self._content.AbsoluteSize.X
        local useSingle = mobile or width < 560
        if useSingle then
            tab._left.Size = UDim2.new(1, 0, 0, 0)
            tab._right.Size = UDim2.new(1, 0, 0, 0)
            for _, sec in ipairs(tab._sections) do
                sec._frame.Parent = tab._left
                sec._frame.LayoutOrder = sec._order
            end
            tab._right.Visible = false
            tab._left.Visible = true
        else
            tab._right.Visible = true
            for _, sec in ipairs(tab._sections) do
                sec._frame.Parent = sec._desktopParent or tab._left
            end
        end
    end
end

function UI:CreateWindow(config)
    config = config or {}
    local win = setmetatable({
        _requestedSize = config.Size or UDim2.fromOffset(760, 540),
        _railWidth = 178, _tabs = {}, _connections = {}, _open = true, _tabSequence = 0,
        _selected = nil, _settingsTab = nil,
    }, Window)

    local old = GuiParent:FindFirstChild("KhfreshBentoUI")
    if old then pcall(function() old:Destroy() end) end

    local gui = make("ScreenGui", {
        Name = "KhfreshBentoUI", ResetOnSpawn = false, IgnoreGuiInset = true,
        DisplayOrder = 2147483645, ZIndexBehavior = Enum.ZIndexBehavior.Global,
    }, GuiParent)
    pcall(function() if syn and syn.protect_gui then syn.protect_gui(gui) end end)
    win._gui = gui

    local shell = make("Frame", {
        Name = "Shell", BackgroundColor3 = C.canvas, BorderSizePixel = 0,
        Size = clampWindowSize(win._requestedSize), Position = UDim2.fromScale(0.5, 0.5),
        AnchorPoint = Vector2.new(0.5, 0.5), ClipsDescendants = true, Active = true,
    }, gui)
    corner(shell, 24); outline(shell, C.line, 0.26, 1)
    win._shell = shell

    if type(config.Background) == "string" and config.Background ~= "" then
        win._background = make("ImageLabel", {
            Name = "Background", BackgroundTransparency = 1, BorderSizePixel = 0,
            Size = UDim2.fromScale(1, 1), Image = config.Background,
            ImageTransparency = tonumber(config.BackgroundImageTransparency) or 0.42,
            ScaleType = Enum.ScaleType.Crop, ZIndex = 0,
        }, shell)
        win._backgroundTint = make("Frame", {
            Name = "BackgroundTint", BackgroundColor3 = Color3.fromRGB(8, 10, 14), BackgroundTransparency = 0.74,
            BorderSizePixel = 0, Size = UDim2.fromScale(1, 1), ZIndex = 1,
        }, shell)
    end

    local top = make("Frame", {
        Name = "TopBar", BackgroundColor3 = C.header, BorderSizePixel = 0,
        Size = UDim2.new(1, 0, 0, 82), ZIndex = 20,
    }, shell)
    corner(top, 22); win._top = top

    win._logoHolder = make("Frame", {
        Name = "LogoHolder", BackgroundColor3 = C.row, BorderSizePixel = 0,
        Position = UDim2.fromOffset(14, 14), Size = UDim2.fromOffset(54, 54), ZIndex = 22,
    }, top)
    corner(win._logoHolder, 16)
    win._logoFallback = text(win._logoHolder, "K", 28, C.secondary, true)
    win._logoFallback.Size = UDim2.fromScale(1, 1)
    win._logoFallback.TextXAlignment = Enum.TextXAlignment.Center
    win._logoFallback.ZIndex = 23
    if type(config.Logo) == "string" and config.Logo ~= "" then
        win._logo = make("ImageLabel", {BackgroundTransparency = 1, BorderSizePixel = 0, Size = UDim2.fromScale(1, 1), Image = config.Logo, ScaleType = Enum.ScaleType.Fit, ZIndex = 24, ImageTransparency = 0}, win._logoHolder)
    else
        win._logo = packedIcon(win._logoHolder, config.Icon or "layout-dashboard", UDim2.fromOffset(16, 16), UDim2.fromOffset(22, 22), C.secondary, 24)
    end

    win._brandText = text(top, config.Title or "Khfresh Hub", 18, C.text, true)
    win._brandText.Position = UDim2.fromOffset(82, 14); win._brandText.Size = UDim2.new(1, -190, 0, 28); win._brandText.ZIndex = 22
    win._authorText = text(top, config.Author or "Khfresh Bento UI", 11, C.muted, false)
    win._authorText.Position = UDim2.fromOffset(82, 43); win._authorText.Size = UDim2.new(1, -190, 0, 20); win._authorText.ZIndex = 22

    win._minBtn = make("TextButton", {Text = "", BackgroundColor3 = C.row, BorderSizePixel = 0, Size = UDim2.fromOffset(34, 34), Position = UDim2.new(1, -86, 0, 24), AutoButtonColor = false, ZIndex = 25}, top)
    corner(win._minBtn, 11); packedIcon(win._minBtn, "minus", UDim2.fromOffset(8, 8), UDim2.fromOffset(18, 18), C.secondary, 26)
    win._minBtn.Activated:Connect(function() win:Toggle() end)
    win._closeBtn = make("TextButton", {Text = "", BackgroundColor3 = C.row, BorderSizePixel = 0, Size = UDim2.fromOffset(34, 34), Position = UDim2.new(1, -44, 0, 24), AutoButtonColor = false, ZIndex = 25}, top)
    corner(win._closeBtn, 11); packedIcon(win._closeBtn, "x", UDim2.fromOffset(8, 8), UDim2.fromOffset(18, 18), C.secondary, 26)
    win._closeBtn.Activated:Connect(function() win:Destroy() end)

    win._rail = make("ScrollingFrame", {
        Name = "Rail", BackgroundColor3 = C.rail, BorderSizePixel = 0,
        Position = UDim2.fromOffset(0, 82), Size = UDim2.new(0, 178, 1, -82),
        CanvasSize = UDim2.new(), AutomaticCanvasSize = Enum.AutomaticSize.Y,
        ScrollBarThickness = 2, ScrollBarImageColor3 = C.muted, ScrollingDirection = Enum.ScrollingDirection.Y,
        ZIndex = 15,
    }, shell)
    list(win._rail, 7); pad(win._rail, 10, 10, 12, 36)
    win._railDivider = make("Frame", {BackgroundColor3 = C.lineSoft, BorderSizePixel = 0, Position = UDim2.new(1, -1, 0, 0), Size = UDim2.new(0, 1, 1, 0), ZIndex = 16}, win._rail)

    win._content = make("Frame", {
        Name = "Content", BackgroundColor3 = C.canvas, BackgroundTransparency = 0.36, BorderSizePixel = 0,
        Position = UDim2.fromOffset(178, 82), Size = UDim2.new(1, -178, 1, -82), ClipsDescendants = false, ZIndex = 10,
    }, shell)

    win._dragHandle = make("TextButton", {
        Name = "DragHandle", Text = "", BackgroundTransparency = 1, BorderSizePixel = 0,
        Position = UDim2.new(0.5, -80, 1, -20), Size = UDim2.fromOffset(190, 20), AutoButtonColor = false, ZIndex = 100,
    }, shell)
    local dragLine = make("Frame", {BackgroundColor3 = C.muted, BackgroundTransparency = 0.15, BorderSizePixel = 0, Position = UDim2.new(0.5, -38, 0.5, -2), Size = UDim2.fromOffset(84, 4), ZIndex = 101}, win._dragHandle)
    corner(dragLine, 999)

    win._resizeHandle = make("TextButton", {
        Name = "ResizeHandle", Text = "", BackgroundTransparency = 1, BorderSizePixel = 0,
        AnchorPoint = Vector2.new(1, 1), Position = UDim2.new(1, 0, 1, 0), Size = UDim2.fromOffset(36, 36),
        AutoButtonColor = false, ZIndex = 100,
    }, shell)
    for i = 1, 4 do
        local len = 5 + i * 3
        local line = make("Frame", {
            BackgroundColor3 = C.muted, BorderSizePixel = 0,
            Position = UDim2.new(1, -len - 2, 1, -3 - i * 5), Size = UDim2.fromOffset(len, 1),
            Rotation = -45, ZIndex = 101,
        }, win._resizeHandle)
        line.AnchorPoint = Vector2.new(1, 0.5)
    end

    table.insert(UI._windows, win)
    installMove(win)
    installResize(win)

    win._cameraConnection = nil
    local camera = workspace.CurrentCamera
    if camera then
        win._cameraConnection = camera:GetPropertyChangedSignal("ViewportSize"):Connect(function()
            local oldSize = win._manualSize
            if oldSize then win._shell.Size = clampWindowSize(oldSize) else win._shell.Size = clampWindowSize(win._requestedSize) end
            win:_refreshLayout()
        end)
        table.insert(win._connections, win._cameraConnection)
    end
    win:_refreshLayout()
    gui.Enabled = true
    shell.Visible = true
    return win
end

function Window:CreateTab(nameOrConfig, icon)
    local config = type(nameOrConfig) == "table" and nameOrConfig or {Title = nameOrConfig, Icon = icon}
    local title = tostring(config.Title or config.Name or "Tab")
    local iconName = config.Icon or "circle"
    self._tabSequence = self._tabSequence + 1

    local btn = make("TextButton", {
        Name = "Tab_" .. safeName(title), Text = "", BackgroundColor3 = C.row, BorderSizePixel = 0,
        Size = UDim2.new(1, 0, 0, 48), AutoButtonColor = false, LayoutOrder = self._tabSequence, ZIndex = 17,
    }, self._rail)
    corner(btn, 15)
    local ico = packedIcon(btn, iconName, UDim2.fromOffset(12, 12), UDim2.fromOffset(24, 24), C.muted, 18)
    local lbl = text(btn, title, 12, C.secondary, true)
    lbl.Position = UDim2.fromOffset(46, 0); lbl.Size = UDim2.new(1, -54, 1, 0); lbl.ZIndex = 19

    local page = make("ScrollingFrame", {
        Name = "Page_" .. safeName(title), BackgroundTransparency = 1, BorderSizePixel = 0,
        Size = UDim2.fromScale(1, 1), CanvasSize = UDim2.new(), AutomaticCanvasSize = Enum.AutomaticSize.Y,
        ScrollBarThickness = 4, ScrollBarImageColor3 = C.muted, ScrollingDirection = Enum.ScrollingDirection.Y,
        Visible = false, ZIndex = 12, ClipsDescendants = false,
    }, self._content)
    page.ScrollingEnabled = true
    page.AutomaticCanvasSize = Enum.AutomaticSize.Y
    local pageLayout = make("UIListLayout", {
        FillDirection = Enum.FillDirection.Vertical,
        SortOrder = Enum.SortOrder.LayoutOrder,
        Padding = UDim.new(0, 10),
    }, page)
    pageLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
    pad(page, 16, 16, 16, 34)

    local tab = setmetatable({
        _window = self, _btn = btn, _icon = ico, _label = lbl, _page = page,
        _title = title, _iconName = iconName, _order = 0, _sections = {}, _settingsBento = string.lower(title) == "settings",
    }, Tab)
    pageLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
        page.CanvasSize = UDim2.new(0, 0, 0, pageLayout.AbsoluteContentSize.Y + 24)
    end)
    table.insert(self._tabs, tab)
    if tab._settingsBento then self._settingsTab = tab end
    buildSectionHost(tab)

    btn.Activated:Connect(function() self:SelectTab(tab) end)
    if #self._tabs == 1 then self:SelectTab(tab) end
    self:_refreshLayout()
    return tab
end

function Window:GetTab(title)
    local wanted = string.lower(tostring(title or ""))
    for _, tab in ipairs(self._tabs) do
        if string.lower(tab._title) == wanted then return tab end
    end
end

function Window:SelectTab(index)
    local tab = type(index) == "table" and index or self._tabs[tonumber(index) or 1]
    if not tab then return end
    if ActiveDropdown then pcall(function() ActiveDropdown:Destroy() end); ActiveDropdown = nil end
    self._selected = tab
    for _, t in ipairs(self._tabs) do
        local on = t == tab
        t._page.Visible = on
        t._btn.BackgroundColor3 = on and C.lineSoft or C.row
        t._label.TextColor3 = on and C.text or C.secondary
        iconSetColor(t._icon, on and C.secondary or C.muted)
    end
end

function Window:Toggle()
    self._open = not self._open
    if self._open then
        self._shell.Visible = true
        self._shell.BackgroundTransparency = 0.08
        tween(self._shell, Motion.smooth, {BackgroundTransparency = 0})
    else
        tween(self._shell, Motion.fast, {BackgroundTransparency = 0.08})
        task.delay(0.11, function()
            if not self._open and self._shell then self._shell.Visible = false end
        end)
    end
end
function Window:Minimize() self._open = false; self._shell.Visible = false end
function Window:Open() self._open = true; self._shell.Visible = true end
function Window:Destroy()
    for _, c in ipairs(self._connections or {}) do pcall(function() c:Disconnect() end) end
    for _, t in ipairs(self._tabs or {}) do
        pcall(function() if t._settingsLeftConn then t._settingsLeftConn:Disconnect() end end)
        pcall(function() if t._settingsRightConn then t._settingsRightConn:Disconnect() end end)
    end
    if #UI._windows <= 1 then
        for _, image in ipairs(UI._iconImages) do pcall(function() image:Destroy() end) end
        table.clear(UI._iconImages)
    end
    if self._floatingGui then pcall(function() self._floatingGui:Destroy() end) end
    if self._gui then pcall(function() self._gui:Destroy() end) end
    for i, v in ipairs(UI._windows) do if v == self then table.remove(UI._windows, i); break end end
end
function Window:ToggleAcrylic() end
function Window:SetBackground(asset, transparency)
    if not self._background then
        self._background = make("ImageLabel", {Name = "Background", BackgroundTransparency = 1, BorderSizePixel = 0, Size = UDim2.fromScale(1, 1), ScaleType = Enum.ScaleType.Crop, ZIndex = 0}, self._shell)
        self._backgroundTint = make("Frame", {Name = "BackgroundTint", BackgroundColor3 = Color3.fromRGB(8, 10, 14), BackgroundTransparency = 0.74, BorderSizePixel = 0, Size = UDim2.fromScale(1, 1), ZIndex = 1}, self._shell)
    end
    self._background.Image = tostring(asset or "")
    self._background.ImageTransparency = tonumber(transparency) or 0.42
end
function Window:SetLogo(asset)
    if self._logo then self._logo:Destroy() end
    self._logo = make("ImageLabel", {Name = "Logo", BackgroundTransparency = 1, BorderSizePixel = 0, Size = UDim2.fromScale(1, 1), Image = tostring(asset or ""), ScaleType = Enum.ScaleType.Fit, ZIndex = 23}, self._logoHolder)
end
function Window:_setFloatingVisible(show, immediate)
    local sg = self._floatingGui
    local btn = self._floatingButton
    if not sg or not sg.Parent or not btn then
        self._floatingVisible = show == true
        return
    end
    self._floatingVisible = show == true
    if show then
        sg.Enabled = true
        btn.BackgroundTransparency = 1
        local scale = btn:FindFirstChildOfClass("UIScale")
        if scale then scale.Scale = immediate and 1 or 0.82 end
        local iconHolder = btn:FindFirstChildOfClass("Frame")
        if immediate then
            btn.BackgroundTransparency = 0
            if scale then scale.Scale = 1 end
        else
            tween(btn, Motion.smooth, {BackgroundTransparency = 0})
            if scale then tween(scale, Motion.spring, {Scale = 1}) end
            if iconHolder then
                for _, obj in ipairs(iconHolder:GetDescendants()) do
                    if obj:IsA("ImageLabel") then obj.ImageTransparency = 1; tween(obj, Motion.smooth, {ImageTransparency = 0}) end
                    if obj:IsA("Frame") then
                        local original = obj:GetAttribute("KhfreshOriginalTransparency")
                        if original ~= nil then
                            obj.BackgroundTransparency = 1
                            tween(obj, Motion.smooth, {BackgroundTransparency = original})
                        end
                    end
                end
            end
        end
    else
        local scale = btn:FindFirstChildOfClass("UIScale")
        if immediate then
            if scale then scale.Scale = 0.82 end
            btn.BackgroundTransparency = 1
            sg.Enabled = false
            return
        end
        tween(btn, Motion.fast, {BackgroundTransparency = 1})
        if scale then tween(scale, Motion.fast, {Scale = 0.82}) end
        task.delay(0.14, function()
            if self._floatingVisible == false and sg.Parent then sg.Enabled = false end
        end)
    end
end

function Window:SetFloatingVisible(v)
    self:_setFloatingVisible(v ~= false, false)
end

function Window:CreateFloatingToggle(config)
    config = config or {}
    if self._floatingGui then pcall(function() self._floatingGui:Destroy() end) end
    local sg = make("ScreenGui", {
        Name = "KhfreshFloatingGui", ResetOnSpawn = false, IgnoreGuiInset = true,
        DisplayOrder = 2147483630, ZIndexBehavior = Enum.ZIndexBehavior.Global,
    }, GuiParent)
    self._floatingGui = sg
    self._floatingVisible = true
    local mobile = isMobile()
    local size = mobile and 50 or 54
    local btn = make("TextButton", {
        Name = "FloatingButton", Text = "", BackgroundColor3 = C.header, BorderSizePixel = 0,
        Size = UDim2.fromOffset(size, size), Position = UDim2.new(1, -(size + 16), 1, -(size + 18)),
        AutoButtonColor = false, Active = true, ZIndex = 10, BackgroundTransparency = 1,
    }, sg)
    corner(btn, mobile and 16 or 17); outline(btn, C.lineSoft, 0.18, 1)
    self._floatingButton = btn
    local iconHolder = packedIcon(btn, config.Icon or "volleyball", UDim2.fromOffset(size * 0.20, size * 0.20), UDim2.fromOffset(size * 0.60, size * 0.60), C.secondary, 12)
    local scale = make("UIScale", {Scale = 0.82}, btn)
    btn.Activated:Connect(function() self:Toggle() end)
    local function reposition()
        if not btn or not btn.Parent then return end
        local m = isMobile()
        local sz = m and 50 or 54
        btn.Size = UDim2.fromOffset(sz, sz)
        btn.Position = UDim2.new(1, -(sz + 16), 1, -(sz + 18))
    end
    local camera = workspace.CurrentCamera
    if camera then table.insert(self._connections, camera:GetPropertyChangedSignal("ViewportSize"):Connect(reposition)) end
    self:_setFloatingVisible(true, false)
    return sg
end

function Tab:CreateHeader(config)
    config = type(config) == "table" and config or {Title = tostring(config or "")}
    self._headerSeq = (self._headerSeq or 0) + 1
    local frame = make("Frame", {BackgroundTransparency = 1, BorderSizePixel = 0, Size = UDim2.new(1, 0, 0, 54), LayoutOrder = self._headerSeq}, self._headerHost)
    if config.Icon then packedIcon(frame, config.Icon, UDim2.fromOffset(0, 15), UDim2.fromOffset(20, 20), C.accent, 5) end
    local left = config.Icon and 28 or 0
    local t = text(frame, config.Title or "", 17, C.text, true); t.Position = UDim2.fromOffset(left, 0); t.Size = UDim2.new(1, -left, 0, 28)
    local s = text(frame, config.Subtitle or config.Desc or "", 11, C.muted, false); s.Position = UDim2.fromOffset(left, 29); s.Size = UDim2.new(1, -left, 0, 20)
    return frame
end

function Tab:_chooseParent(section)
    if not self._settingsBento then return self._listHost end
    local vp = getViewport()
    local mobile = isMobile() or self._window._content.AbsoluteSize.X < 560
    if mobile then return self._left end
    if section._side == "right" then return self._right end
    if section._side == "left" then return self._left end
    local count = #self._sections
    return (count % 2 == 1) and self._left or self._right
end

function Tab:_moveSettingsSections()
    if not self._settingsBento then return end
    local mobile = isMobile() or self._window._content.AbsoluteSize.X < 560
    if mobile then
        self._right.Visible = false
        self._left.Visible = true
        for _, section in ipairs(self._sections) do
            section._frame.Parent = self._left
            section._frame.LayoutOrder = section._sectionOrder
        end
    else
        self._right.Visible = true
        for _, section in ipairs(self._sections) do
            section._frame.Parent = section._desktopParent or self._left
        end
    end
end

function Tab:_directSection()
    if self._direct then return self._direct end
    local s = self:CreateSection({Title = "", HideHeader = true})
    self._direct = s
    return s
end

function Tab:CreateSection(nameOrConfig, side)
    local config = type(nameOrConfig) == "table" and nameOrConfig or {Title = nameOrConfig, Side = side}
    local name = tostring(config.Title or config.Name or "Section")
    local sideName = type(config.Side) == "string" and string.lower(config.Side) or nil
    self._order = (self._order or 0) + 1

    local frame = make("Frame", {
        Name = "Section_" .. safeName(name), BackgroundColor3 = C.card, BorderSizePixel = 0,
        Size = UDim2.new(1, 0, 0, 57), ClipsDescendants = false, LayoutOrder = self._order, ZIndex = 30,
    }, nil)
    if self._settingsBento then
        corner(frame, 18); outline(frame, C.lineSoft, 0.14, 1)
    else
        frame.BackgroundTransparency = 1
    end

    local header = make("Frame", {Name = "SectionHeader", BackgroundTransparency = 1, BorderSizePixel = 0, Size = UDim2.new(1, 0, 0, 45), ZIndex = 31}, frame)
    if not config.HideHeader and name ~= "" then
        packedIcon(header, config.Icon or "shapes", UDim2.fromOffset(12, 13), UDim2.fromOffset(19, 19), C.muted, 34)
        local title = text(header, name, 13, C.text, true)
        title.Position = UDim2.fromOffset(40, 0); title.Size = UDim2.new(1, -52, 1, 0); title.ZIndex = 34
    else
        header.Visible = false
    end

    local bodyTop = (config.HideHeader or name == "") and 0 or 45
    local body = make("Frame", {
        Name = "Body", BackgroundTransparency = 1, BorderSizePixel = 0,
        Position = UDim2.fromOffset(0, bodyTop), Size = UDim2.new(1, 0, 0, 0),
        ZIndex = 32,
    }, frame)
    pad(body, 10, 10, 0, 12)
    local lay = list(body, 8)
    local section = setmetatable({
        _tab = self, _frame = frame, _body = body, _layout = lay, _name = name,
        _side = sideName, _sectionOrder = self._order, _rowOrder = 0, _controls = {},
    }, Section)
    frame.LayoutOrder = section._sectionOrder
    table.insert(self._sections, section)

    lay:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function() updateSectionHeight(section) end)
    local parent = self:_chooseParent(section)
    section._desktopParent = parent
    section._frame.Parent = parent
    if self._settingsBento then self:_moveSettingsSections() end
    updateSectionHeight(section)
    return section
end

function Tab:CreateButton(config) return self:_directSection():CreateButton(config) end
function Tab:CreateToggle(config) return self:_directSection():CreateToggle(config) end
function Tab:CreateDropdown(config) return self:_directSection():CreateDropdown(config) end
function Tab:CreateMultiDropdown(config) return self:_directSection():CreateMultiDropdown(config) end
function Tab:CreateTextbox(config) return self:_directSection():CreateTextbox(config) end
function Tab:CreateSlider(config) return self:_directSection():CreateSlider(config) end
function Tab:CreateColorpicker(config) return self:_directSection():CreateColorpicker(config) end
function Tab:CreateLabel(value) return self:_directSection():CreateLabel(value) end

local function addRow(section, name, iconName, height)
    section._rowOrder = (section._rowOrder or 0) + 1
    local row = make("Frame", {
        Name = "Row_" .. safeName(name), BackgroundColor3 = C.row, BorderSizePixel = 0,
        Size = UDim2.new(1, 0, 0, height or 48), LayoutOrder = section._rowOrder,
        ClipsDescendants = false, ZIndex = 60,
    }, section._body)
    corner(row, 13); outline(row, C.lineSoft, 0.30, 1)
    if iconName then packedIcon(row, iconName, UDim2.fromOffset(11, 11), UDim2.fromOffset(23, 23), C.muted, 63) end
    return row
end

function Section:CreateLabel(value)
    local row = addRow(self, "Label", nil, 38)
    local t = text(row, value, 12, C.secondary, false); t.Position = UDim2.fromOffset(12, 0); t.Size = UDim2.new(1, -24, 1, 0); t.ZIndex = 63
    return row
end

function Section:CreateButton(config)
    config = config or {}
    local name = config.Name or config.Title or "Button"
    local row = addRow(self, name, config.Icon, 48)
    local left = config.Icon and 42 or 14
    local t = text(row, name, 13, C.text, true); t.Position = UDim2.fromOffset(left, 0); t.Size = UDim2.new(1, -58, 1, 0); t.ZIndex = 64
    packedIcon(row, "chevron-right", UDim2.new(1, -31, 0.5, -9), UDim2.fromOffset(18, 18), C.muted, 64)
    local hit = hitButton(row, 90)
    hit.Activated:Connect(function() if config.Callback then task.spawn(config.Callback) end end)
    return {_frame = row}
end

function Section:CreateToggle(config)
    config = config or {}
    local name = config.Name or config.Title or "Toggle"
    local state = config.Default == true or config.Value == true
    local row = addRow(self, name, config.Icon, 50)
    local left = config.Icon and 42 or 14
    local title = text(row, name, 13, C.text, true); title.Position = UDim2.fromOffset(left, 0); title.Size = UDim2.new(1, -86, 1, 0); title.ZIndex = 64
    local track = make("Frame", {BackgroundColor3 = state and C.accent or C.rowPressed, BorderSizePixel = 0, AnchorPoint = Vector2.new(1, 0.5), Position = UDim2.new(1, -14, 0.5, 0), Size = UDim2.fromOffset(48, 28), ZIndex = 64}, row)
    corner(track, 14)
    local knob = make("Frame", {BackgroundColor3 = C.text, BorderSizePixel = 0, Size = UDim2.fromOffset(22, 22), Position = state and UDim2.new(1, -25, 0.5, -11) or UDim2.fromOffset(3, 3), ZIndex = 65}, track)
    corner(knob, 11)
    local hit = hitButton(row, 90)
    local function set(v, emit)
        state = v == true
        tween(track, Motion.base, {BackgroundColor3 = state and C.accent or C.rowPressed})
        tween(knob, Motion.base, {Position = state and UDim2.new(1, -25, 0.5, -11) or UDim2.fromOffset(3, 3)})
        if emit and config.Callback then task.spawn(config.Callback, state) end
    end
    hit.Activated:Connect(function() set(not state, true) end)
    local ref = { _frame = row, Set = function(_, v) set(v, true) end, SetValue = function(_, v) set(v, true) end, Get = function() return state end }
    table.insert(self._controls, ref)
    return ref
end

local ActiveDropdown
local function getDropdownOverlay()
    local gui = UI._dropdownOverlay
    if gui and gui.Parent then return gui end
    gui = make("ScreenGui", {Name = "KhfreshDropdownOverlay", ResetOnSpawn = false, IgnoreGuiInset = true, DisplayOrder = 2147483647, ZIndexBehavior = Enum.ZIndexBehavior.Global}, GuiParent)
    UI._dropdownOverlay = gui
    return gui
end

local function closeDropdown()
    if ActiveDropdown and ActiveDropdown.Parent then pcall(function() ActiveDropdown:Destroy() end) end
    ActiveDropdown = nil
end

local function buildDropdownMenu(row, options, selected, multi, callback)
    closeDropdown()
    local overlay = getDropdownOverlay()
    local pos = row.AbsolutePosition
    local size = row.AbsoluteSize
    local vp = getViewport()
    local h = math.min(260, math.max(36, #options * 34 + 10))
    local menuW = math.min(320, math.max(190, size.X - 16))
    local x = math.clamp(pos.X + 8, 6, math.max(6, vp.X - menuW - 6))
    local belowY = pos.Y + size.Y + 4
    local y = belowY
    if y + h > vp.Y - 6 then y = math.max(6, pos.Y - h - 4) end
    local menu = make("ScrollingFrame", {
        Name = "DropdownMenu", BackgroundColor3 = C.shell, BorderSizePixel = 0,
        Position = UDim2.fromOffset(x, y),
        Size = UDim2.fromOffset(menuW, h),
        CanvasSize = UDim2.new(), AutomaticCanvasSize = Enum.AutomaticSize.Y,
        ScrollBarThickness = 2, ScrollBarImageColor3 = C.muted, ZIndex = 5000,
    }, overlay)
    corner(menu, 12); outline(menu, C.line, 0.10, 1); pad(menu, 5, 5, 5, 5)
    local lay = list(menu, 4)
    ActiveDropdown = menu
    for _, opt in ipairs(options) do
        local rowBtn = make("TextButton", {Text = "", BackgroundColor3 = C.row, BorderSizePixel = 0, Size = UDim2.new(1, 0, 0, 34), AutoButtonColor = false, ZIndex = 5001}, menu)
        corner(rowBtn, 9)
        local label = text(rowBtn, opt, 11, C.secondary, false); label.Position = UDim2.fromOffset(10, 0); label.Size = UDim2.new(1, -20, 1, 0); label.ZIndex = 5003
        if multi and selected[opt] then
            packedIcon(rowBtn, "check", UDim2.new(1, -27, 0.5, -8), UDim2.fromOffset(16, 16), C.secondary, 5004)
        end
        rowBtn.Activated:Connect(function()
            if multi then
                selected[opt] = not selected[opt]
                if callback then task.spawn(callback, selected) end
                buildDropdownMenu(row, options, selected, multi, callback)
            else
                closeDropdown()
                if callback then task.spawn(callback, opt) end
            end
        end)
    end
    return menu
end

function Section:CreateDropdown(config)
    config = config or {}
    local name = config.Name or config.Title or "Dropdown"
    local rawOptions = config.Options or config.Values or {}
    local options = {}
    for _, v in ipairs(rawOptions) do
        if type(v) == "table" then v = v.Title or v.Name or v.Value or v.Text or v[1] end
        if v ~= nil then options[#options + 1] = tostring(v) end
    end
    local selected = tostring(config.Default or config.Value or options[1] or "Select")
    local row = addRow(self, name, config.Icon, 52)
    local left = config.Icon and 42 or 14
    local title = text(row, name, 12, C.secondary, true); title.Position = UDim2.fromOffset(left, 0); title.Size = UDim2.new(0.42, -left, 1, 0); title.ZIndex = 64
    local value = text(row, selected, 12, C.text, false); value.Position = UDim2.new(0.42, 0, 0, 0); value.Size = UDim2.new(0.58, -48, 1, 0); value.TextXAlignment = Enum.TextXAlignment.Right; value.ZIndex = 64
    packedIcon(row, "chevron-down", UDim2.new(1, -32, 0.5, -8), UDim2.fromOffset(17, 17), C.muted, 65)
    local hit = hitButton(row, 90)
    local open = false
    local function choose(v)
        selected = tostring(v); value.Text = selected
        if config.Callback then task.spawn(config.Callback, selected) end
    end
    hit.Activated:Connect(function()
        open = not open
        if open then
            buildDropdownMenu(row, options, {}, false, function(v) choose(v) end)
        else
            closeDropdown()
        end
    end)
    return { _frame = row, Set = function(_, v) choose(v) end, SetValue = function(_, v) choose(v) end, Get = function() return selected end }
end

function Section:CreateMultiDropdown(config)
    config = config or {}
    local name = config.Name or config.Title or "Multi Dropdown"
    local rawOptions = config.Options or config.Values or {}
    local options = {}
    for _, v in ipairs(rawOptions) do
        if type(v) == "table" then v = v.Title or v.Name or v.Value or v.Text or v[1] end
        if v ~= nil then options[#options + 1] = tostring(v) end
    end
    local selected = {}
    if type(config.Default) == "table" then for _, v in ipairs(config.Default) do selected[tostring(v)] = true end end
    local row = addRow(self, name, config.Icon, 52)
    local left = config.Icon and 42 or 14
    local title = text(row, name, 12, C.secondary, true); title.Position = UDim2.fromOffset(left, 0); title.Size = UDim2.new(0.42, -left, 1, 0); title.ZIndex = 64
    local value = text(row, "None", 11, C.text, false); value.Position = UDim2.new(0.42, 0, 0, 0); value.Size = UDim2.new(0.58, -48, 1, 0); value.TextXAlignment = Enum.TextXAlignment.Right; value.ZIndex = 64
    packedIcon(row, "chevron-down", UDim2.new(1, -32, 0.5, -8), UDim2.fromOffset(17, 17), C.muted, 65)
    local function updateLabel()
        local arr = {}
        for _, v in ipairs(options) do if selected[v] then arr[#arr + 1] = v end end
        value.Text = #arr == 0 and "None" or (#arr <= 2 and table.concat(arr, ", ") or (tostring(#arr) .. " selected"))
    end
    updateLabel()
    local hit = hitButton(row, 90)
    hit.Activated:Connect(function()
        if ActiveDropdown then closeDropdown() end
        buildDropdownMenu(row, options, selected, true, function(sel)
            local arr = {}
            for _, v in ipairs(options) do if sel[v] then arr[#arr + 1] = v end end
            updateLabel()
            if config.Callback then task.spawn(config.Callback, arr) end
        end)
    end)
    return {
        _frame = row,
        Set = function(_, v)
            if type(v) == "table" then
                table.clear(selected); for _, x in ipairs(v) do selected[tostring(x)] = true end; updateLabel()
            end
        end,
        Get = function() local out = {}; for _, v in ipairs(options) do if selected[v] then out[#out + 1] = v end end; return out end,
    }
end

function Section:CreateTextbox(config)
    config = config or {}
    local name = config.Name or config.Title or "Input"
    local row = addRow(self, name, config.Icon, 52)
    local left = config.Icon and 42 or 14
    local title = text(row, name, 12, C.secondary, true); title.Position = UDim2.fromOffset(left, 0); title.Size = UDim2.new(0.40, -left, 1, 0); title.ZIndex = 64
    local box = make("TextBox", {
        BackgroundColor3 = C.shell, BorderSizePixel = 0, Text = tostring(config.Default or config.Value or ""),
        PlaceholderText = tostring(config.Placeholder or ""), PlaceholderColor3 = C.muted, TextColor3 = C.text,
        TextSize = 12, Font = Enum.Font.Gotham, ClearTextOnFocus = false, TextXAlignment = Enum.TextXAlignment.Left,
        Size = UDim2.new(0.58, -8, 0, 34), Position = UDim2.new(0.40, 0, 0.5, -17), ZIndex = 68,
    }, row)
    corner(box, 10); outline(box, C.lineSoft, 0.16, 1); pad(box, 10, 10, 0, 0)
    local function emit() if config.Callback then task.spawn(config.Callback, box.Text) end end
    box.FocusLost:Connect(emit)
    return { _frame = row, _input = box, Set = function(_, v) box.Text = tostring(v or ""); emit() end, SetValue = function(_, v) box.Text = tostring(v or ""); emit() end, Get = function() return box.Text end }
end

function Section:CreateSlider(config)
    config = config or {}
    local name = config.Name or config.Title or "Slider"
    local min = tonumber(config.Min or config.Minimum or 0) or 0
    local max = tonumber(config.Max or config.Maximum or 100) or 100
    if max <= min then max = min + 1 end
    local current = math.clamp(tonumber(config.Default or config.Value or min) or min, min, max)
    local row = addRow(self, name, config.Icon, 66)
    local left = config.Icon and 42 or 14
    local title = text(row, name, 12, C.secondary, true); title.Position = UDim2.fromOffset(left, 4); title.Size = UDim2.new(0.55, -left, 0, 24); title.ZIndex = 64
    local value = text(row, tostring(current), 11, C.text, true); value.Position = UDim2.new(1, -70, 0, 4); value.Size = UDim2.fromOffset(58, 24); value.TextXAlignment = Enum.TextXAlignment.Right; value.ZIndex = 64
    local track = make("Frame", {BackgroundColor3 = C.shell, BorderSizePixel = 0, Position = UDim2.new(0, 14, 1, -22), Size = UDim2.new(1, -28, 0, 6), ZIndex = 65}, row)
    corner(track, 99)
    local pct = (current - min) / (max - min)
    local fill = make("Frame", {BackgroundColor3 = C.accent, BorderSizePixel = 0, Size = UDim2.new(pct, 0, 1, 0), ZIndex = 66}, track)
    corner(fill, 99)
    local hit = make("TextButton", {Text = "", BackgroundTransparency = 1, BorderSizePixel = 0, Size = UDim2.new(1, 0, 0, 32), Position = UDim2.new(0, 0, 0.5, -16), AutoButtonColor = false, ZIndex = 70}, track)
    local dragging = false
    local function applyX(x, emit)
        local p = math.clamp((x - track.AbsolutePosition.X) / math.max(1, track.AbsoluteSize.X), 0, 1)
        current = math.floor((min + (max - min) * p) + 0.5)
        value.Text = tostring(current); fill.Size = UDim2.new(p, 0, 1, 0)
        if emit and config.Callback then task.spawn(config.Callback, current) end
    end
    hit.InputBegan:Connect(function(input)
        if input.UserInputType ~= Enum.UserInputType.MouseButton1 and input.UserInputType ~= Enum.UserInputType.Touch then return end
        dragging = true; applyX(input.Position.X, true)
    end)
    UserInputService.InputChanged:Connect(function(input)
        if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch) then applyX(input.Position.X, true) end
    end)
    UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then dragging = false end
    end)
    return { _frame = row, Set = function(_, v) applyX(track.AbsolutePosition.X + track.AbsoluteSize.X * math.clamp((tonumber(v) or min - min) / (max - min), 0, 1), true) end, Get = function() return current end }
end

function Section:CreateColorpicker(config)
    config = config or {}
    local name = config.Name or config.Title or "Color"
    local row = addRow(self, name, config.Icon, 48)
    local left = config.Icon and 42 or 14
    local title = text(row, name, 13, C.text, true); title.Position = UDim2.fromOffset(left, 0); title.Size = UDim2.new(1, -86, 1, 0); title.ZIndex = 64
    local swatch = make("Frame", {BackgroundColor3 = typeof(config.Default) == "Color3" and config.Default or C.accent, BorderSizePixel = 0, AnchorPoint = Vector2.new(1, 0.5), Position = UDim2.new(1, -14, 0.5, 0), Size = UDim2.fromOffset(34, 22), ZIndex = 65}, row)
    corner(swatch, 8); outline(swatch, C.line, 0.10, 1)
    local hit = hitButton(row, 90)
    hit.Activated:Connect(function()
        if config.Callback then task.spawn(config.Callback, swatch.BackgroundColor3) end
    end)
    return { _frame = row, Set = function(_, v) if typeof(v) == "Color3" then swatch.BackgroundColor3 = v end end, SetValue = function(_, v) if typeof(v) == "Color3" then swatch.BackgroundColor3 = v end end, Get = function() return swatch.BackgroundColor3 end }
end

function Tab:CreateStatRow(items)
    local row = make("Frame", {BackgroundColor3 = C.card, BorderSizePixel = 0, Size = UDim2.new(1, 0, 0, 48), LayoutOrder = 9998, ZIndex = 30}, self._listHost or self._grid)
    corner(row, 14); outline(row, C.lineSoft, 0.2, 1)
    local x = 12
    for _, item in ipairs(items or {}) do
        local val = text(row, tostring(item.Value or item[2] or "-"), 12, C.text, true); val.Position = UDim2.fromOffset(x, 0); val.Size = UDim2.new(0, 80, 1, 0)
        x = x + 90
    end
    return row
end
function Tab:CreateFeaturedCard(config)
    config = config or {}
    local row = make("Frame", {BackgroundColor3 = C.card, BorderSizePixel = 0, Size = UDim2.new(1, 0, 0, 72), LayoutOrder = 9999, ZIndex = 30}, self._listHost or self._grid)
    corner(row, 16); outline(row, C.lineSoft, 0.2, 1)
    local t = text(row, config.Title or "Featured", 14, C.text, true); t.Position = UDim2.fromOffset(14, 9); t.Size = UDim2.new(1, -28, 0, 22)
    local d = text(row, config.Subtitle or config.Desc or "", 11, C.muted, false); d.Position = UDim2.fromOffset(14, 34); d.Size = UDim2.new(1, -28, 0, 22)
    if config.Callback then hitButton(row, 90).Activated:Connect(config.Callback) end
    return row
end
function Tab:CreateActionRow(config)
    return self:CreateFeaturedCard(config)
end
function Tab:CreateCardGroup(config)
    return self:CreateFeaturedCard(config)
end

function Window:ApplyTheme()
    if self._shell then self._shell.BackgroundColor3 = C.canvas end
    if self._top then self._top.BackgroundColor3 = C.header end
    if self._rail then self._rail.BackgroundColor3 = C.rail end
    for _, tab in ipairs(self._tabs) do
        if tab._btn then tab._btn.BackgroundColor3 = tab == self._selected and C.accentSoft or C.row end
        if tab._icon then iconSetColor(tab._icon, tab == self._selected and C.secondary or C.muted) end
    end
end

return UI
